{{ $app := (include "cassandra-alerts.fullname" .) }}

  {{ if (include "cassandra-alerts.alertsEnabled" .Values.form.alert.enabled) }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ $app }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "cassandra-alerts.labels" . | nindent 4 }}
  {{- if .Values.form.alert.labels }}
  {{- toYaml .Values.form.alert.labels | nindent 4 }}
  {{- end }}
  {{- if .Values.form.alert.annotations }}
annotations:
  {{- toYaml .Values.form.alert.annotations | nindent 4 }}
  {{- end }}
spec:
  groups:
  {{ with .Values.form.alert.groups.database -}}
  {{ if (include "cassandra-alerts.alertGroupEnabled" (list $.Values.form.alert.enabled .)) -}}
  - name: cassandra.database.{{ $.Release.Namespace }}.{{ $app }}.rules
    rules:
    {{ $cassandraDown := index (default dict .rules) "cassandraDown" }}
    {{ if (and $cassandraDown (include "cassandra-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $cassandraDown.enabled $cassandraDown.severity))) -}}
    - alert: CassandraDown
      expr: (count(up{job="{{ $app }}-stats",namespace="{{ $.Release.Namespace }}"} == 0) OR vector(0) ) > {{$cassandraDown.val}}
      for: {{ $cassandraDown.duration }}
      labels:
        severity: {{ $cassandraDown.severity }}
        {{- include "cassandra-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: Cassandra down (instance {{`{{`}} $labels.pod {{`}}`}})
        description: "Cassandra is down on {{`{{`}} $labels.pod {{`}}`}}\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
    {{ $cassandraServiceRespawn := index (default dict .rules) "cassandraServiceRespawn" }}
    {{ if (and $cassandraServiceRespawn (include "cassandra-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $cassandraServiceRespawn.enabled $cassandraServiceRespawn.severity))) -}}
    - alert: CassandraServiceRespawn
      expr: (cassandra_stats{name="java:lang:runtime:uptime"}) < {{$cassandraServiceRespawn.val}}
      for: {{ $cassandraServiceRespawn.duration }}
      labels:
        severity: {{ $cassandraServiceRespawn.severity }}
        {{- include "cassandra-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: Cassandra service restart (instance {{`{{`}} $labels.pod {{`}}`}})
        description: "Cassandra service restart on {{`{{`}} $labels.pod {{`}}`}}\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
    {{ $cassandraConnectionTimeouts := index (default dict .rules) "cassandraConnectionTimeouts" }}
    {{ if (and $cassandraConnectionTimeouts (include "cassandra-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $cassandraConnectionTimeouts.enabled $cassandraConnectionTimeouts.severity))) -}}
    - alert: ConnectionTimeouts
      expr: increase(cassandra_stats{name="org:apache:cassandra:metrics:connection:totaltimeouts:count",job="{{ $app }}-stats",namespace="{{ $.Release.Namespace }}"}[1m]) > {{$cassandraConnectionTimeouts.val}}
      for: {{ $cassandraConnectionTimeouts.duration }}
      labels:
        severity: {{ $cassandraConnectionTimeouts.severity }}
        {{- include "cassandra-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: Cassandra too many connections (> {{$cassandraConnectionTimeouts.val}}%) (instance {{`{{`}} $labels.pod {{`}}`}})
        description: "More than {{$cassandraConnectionTimeouts.val}}% of Cassandra connections are throttled {{`{{`}} $labels.pod {{`}}`}}\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
    {{ $cassandraDroppedMessages := index (default dict .rules) "cassandraDroppedMessages" }}
    {{ if (and $cassandraDroppedMessages (include "cassandra-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $cassandraDroppedMessages.enabled $cassandraDroppedMessages.severity))) -}}
    - alert: DroppedMessages
      expr: cassandra_stats{name=~"org:apache:cassandra:metrics:droppedmessage:.*:count",job="{{ $app }}-stats",namespace="{{ $.Release.Namespace }}"} > 0
      for: {{ $cassandraDroppedMessages.duration }}
      labels:
        severity: {{ $cassandraDroppedMessages.severity }}
        {{- include "cassandra-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: Cassandra has high drop message (instance {{`{{`}} $labels.pod {{`}}`}})
        description: "High drop message for Cassandra {{`{{`}} $labels.pod {{`}}`}}\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
    {{ $cassandraHighReadLatency := index (default dict .rules) "cassandraHighReadLatency" }}
    {{ if (and $cassandraHighReadLatency (include "cassandra-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $cassandraHighReadLatency.enabled $cassandraHighReadLatency.severity))) -}}
    - alert: HighReadLatency
      expr: cassandra_stats{name=~"org:apache:cassandra:metrics:table:kubedb_keyspace:healthcheck_table:coordinatorreadlatency:99thpercentile",job="{{ $app }}-stats",namespace="{{ $.Release.Namespace }}"} > 7000
      for: {{ $cassandraHighReadLatency.duration }}
      labels:
        severity: {{ $cassandraHighReadLatency.severity }}
        {{- include "cassandra-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: Cassandra has high read latency (instance {{`{{`}} $labels.pod {{`}}`}})
        description: "Cassandra has high read latency\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
    {{ $cassandraHighWriteLatency := index (default dict .rules) "cassandraHighWriteLatency" }}
    {{ if (and $cassandraHighWriteLatency (include "cassandra-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $cassandraHighWriteLatency.enabled $cassandraHighWriteLatency.severity))) -}}
    - alert: HighWriteLatency
      expr: cassandra_stats{name=~"org:apache:cassandra:metrics:table:kubedb_keyspace:healthcheck_table:coordinatorwritelatency:99thpercentile",job="{{ $app }}-stats",namespace="{{ $.Release.Namespace }}"} > 7000
      for: {{ $cassandraHighWriteLatency.duration }}
      labels:
        severity: {{ $cassandraHighWriteLatency.severity }}
        {{- include "cassandra-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: Cassandra has high write latency (> {{$cassandraHighWriteLatency.val}}) (instance {{`{{`}} $labels.pod {{`}}`}})
        description: "Cassandra has high write latency on (instance {{`{{`}} $labels.pod {{`}}`}})\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
  {{ end -}}
  {{ end -}}

  {{ with .Values.form.alert.groups.provisioner -}}
  {{ if (include "cassandra-alerts.alertGroupEnabled" (list $.Values.form.alert.enabled .)) -}}
  - name: cassandra.provisioner.{{ $.Release.Namespace }}.{{ $app }}.rules
    rules:
    {{ $appPhaseNotReady := index (default dict .rules) "appPhaseNotReady" }}
    {{ if (and $appPhaseNotReady (include "cassandra-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $appPhaseNotReady.enabled $appPhaseNotReady.severity))) -}}
    - alert: KubeDBCassandraPhaseNotReady
      expr: kubedb_com_cassandra_status_phase{phase="NotReady",app="{{ $app }}",namespace="{{ $.Release.Namespace }}"} == 1
      for: {{ $appPhaseNotReady.duration }}
      labels:
        severity: {{ $appPhaseNotReady.severity }}
        {{- include "cassandra-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: KubeDB Cassandra Phase NotReady (cassandra {{`{{`}} $labels.cassandra {{`}}`}})
        description: "KubeDB Cassandra Phase not ready on {{`{{`}} $labels.cassandra {{`}}`}}\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
    {{ $appPhaseCritical := index (default dict .rules) "appPhaseCritical" }}
    {{ if (and $appPhaseCritical (include "cassandra-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $appPhaseCritical.enabled $appPhaseCritical.severity))) -}}
    - alert: KubeDBCassandraPhaseCritical
      expr: kubedb_com_cassandra_status_phase{phase="Critical",app="{{ $app }}",namespace="{{ $.Release.Namespace }}"} == 1
      for: {{ $appPhaseCritical.duration }}
      labels:
        severity: {{ $appPhaseCritical.severity }}
        {{- include "cassandra-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: KubeDB Cassandra Phase Critical (cassandra {{`{{`}} $labels.cassandra {{`}}`}})
        description: "KubeDB Cassandra Phase Critical {{`{{`}} $labels.cassandra {{`}}`}}\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
  {{ end -}}
  {{ end -}}

{{ end }}