{{ $app := (include "connectcluster-alerts.fullname" .) }}

{{ if (include "connectcluster-alerts.alertsEnabled" .Values.form.alert.enabled) }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ $app }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "connectcluster-alerts.labels" . | nindent 4 }}
{{- if .Values.form.alert.labels }}
    {{- toYaml .Values.form.alert.labels | nindent 4 }}
{{- end }}
{{- if .Values.form.alert.annotations }}
  annotations:
    {{- toYaml .Values.form.alert.annotations | nindent 4 }}
{{- end }}
spec:
  groups:
  {{ with .Values.form.alert.groups.connect -}}
  {{ if (include "connectcluster-alerts.alertGroupEnabled" (list $.Values.form.alert.enabled .)) -}}
  - name: kafka.connectcluster.{{ $.Release.Namespace }}.{{ $app }}.rules
    rules:
    {{ $connectClusterWorkerDown := index (default dict .rules) "connectClusterWorkerDown" }}
    {{ if (and $connectClusterWorkerDown (include "connectcluster-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $connectClusterWorkerDown.enabled $connectClusterWorkerDown.severity))) -}}
    - alert: ConnectClusterWorkerDown
      expr: count(kafka_connect_worker_connector_count{service="{{ $app }}-stats",namespace="{{ $.Release.Namespace }}"}) == 0
      for: {{ $connectClusterWorkerDown.duration }}
      labels:
        severity: {{ $connectClusterWorkerDown.severity }}
        {{- include "connectcluster-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: No ConnectCluster Worker Online! (instance {{`{{`}} $labels.instance {{`}}`}})
        description: "Worker Count is 0.\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
    {{ $connectClusterTooManyConnections := index (default dict .rules) "connectClusterTooManyConnections" }}
    {{ if (and $connectClusterTooManyConnections (include "connectcluster-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $connectClusterTooManyConnections.enabled $connectClusterTooManyConnections.severity))) -}}
    - alert: ConnectClusterTooManyConnections
      expr: sum(kafka_connect_connection_count{service="{{ $app }}-stats",namespace="{{ $.Release.Namespace }}"}) > {{ $connectClusterTooManyConnections.val }}
      for: {{ $connectClusterTooManyConnections.duration }}
      labels:
        severity: {{ $connectClusterTooManyConnections.severity }}
        {{- include "connectcluster-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary:  ConnectCluster too many connections (> {{$connectClusterTooManyConnections.val}}%) (instance {{`{{`}} $labels.pod {{`}}`}})
        description: "More than {{$connectClusterTooManyConnections.val}} of ConnectCluster connections are in use on {{`{{`}} $labels.pod {{`}}`}}\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
    {{ $connectClusterConnectorCount := index (default dict .rules) "connectClusterConnectorCount" }}
    {{ if (and $connectClusterConnectorCount (include "connectcluster-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $connectClusterConnectorCount.enabled $connectClusterConnectorCount.severity))) -}}
    - alert: ConnectClusterConnectorCount
      expr: sum(kafka_connect_worker_connector_count{service="{{ $app }}-stats",namespace="{{ $.Release.Namespace }}"}) > {{ $connectClusterConnectorCount.val }}
      for: {{ $connectClusterConnectorCount.duration }}
      labels:
        severity: {{ $connectClusterConnectorCount.severity }}
        {{- include "connectcluster-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: ConnectCluster has reached connectors threshold. (instance {{`{{`}} $labels.instance {{`}}`}})
        description: "More than {{$connectClusterConnectorCount.val}}% of Connectors are running.\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
    {{ $connectClusterCoordinatorRebalanceFailed := index (default dict .rules) "connectClusterCoordinatorRebalanceFailed" }}
    {{ if (and $connectClusterCoordinatorRebalanceFailed (include "connectcluster-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $connectClusterCoordinatorRebalanceFailed.enabled $connectClusterCoordinatorRebalanceFailed.severity))) -}}
    - alert: ConnectClusterCoordinatorRebalanceFailed
      expr: sum(kafka_connect_coordinator_failed_rebalance_total{service="{{ $app }}-stats",namespace="{{ $.Release.Namespace }}"}) > {{ $connectClusterCoordinatorRebalanceFailed.val }}
      for: {{ $connectClusterCoordinatorRebalanceFailed.duration }}
      labels:
        severity: {{ $connectClusterCoordinatorRebalanceFailed.severity }}
        {{- include "connectcluster-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: ConnectCluster total re-balance exceeds the threshold (instance {{`{{`}} $labels.instance {{`}}`}})
        description: "ConnectCluster coordinator re-balance exceeds {{ $connectClusterCoordinatorRebalanceFailed.val }}%.\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
  {{ end -}}
  {{ end -}}

  {{ with .Values.form.alert.groups.task -}}
  {{ if (include "connectcluster-alerts.alertGroupEnabled" (list $.Values.form.alert.enabled .)) -}}
  - name: kafka.connectcluster.task.{{ $.Release.Namespace }}.{{ $app }}.rules
    rules:
    {{ $connectClusterTaskErrorTotalRetries := index (default dict .rules) "connectClusterTaskErrorTotalRetries" }}
    {{ if (and $connectClusterTaskErrorTotalRetries (include "connectcluster-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $connectClusterTaskErrorTotalRetries.enabled $connectClusterTaskErrorTotalRetries.severity))) -}}
    - alert: ConnectClusterTaskErrorTotalRetries
      expr: sum(kafka_connect_task_error_total_retries{service="{{ $app }}-stats",namespace="{{ $.Release.Namespace }}"}) > {{ $connectClusterTaskErrorTotalRetries.val }}
      for: {{ $connectClusterTaskErrorTotalRetries.duration }}
      labels:
        severity: {{ $connectClusterTaskErrorTotalRetries.severity }}
        {{- include "connectcluster-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: ConnectCluster task error total retries exceeds. (instance {{`{{`}} $labels.instance {{`}}`}})
        description: "ConnectCluster task error total error exceeds the threshold value {{$connectClusterTaskErrorTotalRetries.val}}%.\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
    {{ $connectClusterTaskTotal := index (default dict .rules) "connectClusterTaskTotal" }}
    {{ if (and $connectClusterTaskTotal (include "connectcluster-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $connectClusterTaskTotal.enabled $connectClusterTaskTotal.severity))) -}}
    - alert: ConnectClusterTaskTotal
      expr: sum(kafka_connect_worker_connector_total_task_count{service="{{ $app }}-stats",namespace="{{ $.Release.Namespace }}"}) > {{ $connectClusterTaskTotal.val }}
      for: {{ $connectClusterTaskTotal.duration }}
      labels:
        severity: {{ $connectClusterTaskTotal.severity }}
        {{- include "connectcluster-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: ConnectCluster has reached task threshold. (instance {{`{{`}} $labels.instance {{`}}`}})
        description: "More than {{$connectClusterTaskTotal.val}} task are running.\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
    {{ $connectClusterTaskTotalFailed := index (default dict .rules) "connectClusterTaskTotalFailed" }}
    {{ if (and $connectClusterTaskTotalFailed (include "connectcluster-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $connectClusterTaskTotalFailed.enabled $connectClusterTaskTotalFailed.severity))) -}}
    - alert: ConnectClusterTaskTotalFailed
      expr: sum(kafka_connect_worker_connector_failed_task_count{service="{{ $app }}-stats",namespace="{{ $.Release.Namespace }}"}) > 0
      for: {{ $connectClusterTaskTotalFailed.duration }}
      labels:
        severity: {{ $connectClusterTaskTotalFailed.severity }}
        {{- include "connectcluster-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: Task Failed (instance {{`{{`}} $labels.instance {{`}}`}})
        description: "Some task are failed.\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
    {{ $connectClusterTaskTotalDestroyed := index (default dict .rules) "connectClusterTaskTotalDestroyed" }}
    {{ if (and $connectClusterTaskTotalDestroyed (include "connectcluster-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $connectClusterTaskTotalDestroyed.enabled $connectClusterTaskTotalDestroyed.severity))) -}}
    - alert: ConnectClusterTaskTotalDestroyed
      expr: sum(kafka_connect_worker_connector_destroyed_task_count{service="{{ $app }}-stats",namespace="{{ $.Release.Namespace }}"}) > 0
      for: {{ $connectClusterTaskTotalDestroyed.duration }}
      labels:
        severity: {{ $connectClusterTaskTotalDestroyed.severity }}
        {{- include "connectcluster-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: Task Destroyed (instance {{`{{`}} $labels.instance {{`}}`}})
        description: "Some task are destroyed.\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
  {{ end -}}
  {{ end -}}


  {{ with .Values.form.alert.groups.provisioner -}}
  {{ if (include "connectcluster-alerts.alertGroupEnabled" (list $.Values.form.alert.enabled .)) -}}
  - name: kafka.connectcluster.provisioner.{{ $.Release.Namespace }}.{{ $app }}.rules
    rules:
    {{ $appPhaseNotReady := index (default dict .rules) "appPhaseNotReady" }}
    {{ if (and $appPhaseNotReady (include "connectcluster-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $appPhaseNotReady.enabled $appPhaseNotReady.severity))) -}}
    - alert: KubeDBConnectClusterPhaseNotReady
      expr: kafka_kubedb_com_connectcluster_status_phase{phase="NotReady",app="{{ $app }}",namespace="{{ $.Release.Namespace }}"} == 1
      for: {{ $appPhaseNotReady.duration }}
      labels:
        severity: {{ $appPhaseNotReady.severity }}
        {{- include "connectcluster-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: KubeDB ConnectCluster Phase NotReady (connectcluster {{`{{`}} $labels.connectcluster {{`}}`}})
        description: "KubeDB ConnectCluster Phase not ready on {{`{{`}} $labels.connectcluster {{`}}`}}\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{ end -}}
    {{ $appPhaseCritical := index (default dict .rules) "appPhaseCritical" }}
    {{ if (and $appPhaseCritical (include "connectcluster-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $appPhaseCritical.enabled $appPhaseCritical.severity))) -}}
    - alert: KubeDBConnectClusterPhaseCritical
      expr: kafka_kubedb_com_connectcluster_status_phase{phase="Critical",app="{{ $app }}",namespace="{{ $.Release.Namespace }}"} == 1
      for: {{ $appPhaseCritical.duration }}
      labels:
        severity: {{ $appPhaseCritical.severity }}
        {{- include "connectcluster-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: KubeDB ConnectCluster Phase Critical (connectcluster {{`{{`}} $labels.connectcluster {{`}}`}})
        description: "KubeDB ConnectCluster Phase Critical {{`{{`}} $labels.connectcluster {{`}}`}}\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
  {{ end -}}
  {{ end -}}

{{ end }}
