{{ $app := (include "proxysql-alerts.fullname" .) }}

{{ if (include "proxysql-alerts.alertsEnabled" .Values.form.alert.enabled) }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ $app }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "proxysql-alerts.labels" . | nindent 4 }}
  {{- if .Values.form.alert.labels }}
  {{- toYaml .Values.form.alert.labels | nindent 4 }}
  {{- end }}
  {{- if .Values.form.alert.annotations }}
annotations:
  {{- toYaml .Values.form.alert.annotations | nindent 4 }}
  {{- end }}
spec:
  groups:
  {{ with .Values.form.alert.groups.database -}}
  {{ if (include "proxysql-alerts.alertGroupEnabled" (list $.Values.form.alert.enabled .)) -}}
  - name: proxysql.database.{{ $.Release.Namespace }}.{{ $app }}.rules
    rules:
    {{ $proxysqlInstanceDown := index (default dict .rules) "proxysqlInstanceDown" }}
    {{ if (and $proxysqlInstanceDown (include "proxysql-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $proxysqlInstanceDown.enabled $proxysqlInstanceDown.severity))) -}}
    - alert: ProxySQLInstanceDown
      expr: proxysql_uptime_seconds_total{job="{{ $app }}-stats",namespace="{{ $.Release.Namespace }}"} == 0
      for: {{ $proxysqlInstanceDown.duration }}
      labels:
        severity: {{ $proxysqlInstanceDown.severity }}
        {{- include "proxysql-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: ProxySQL instance down (instance {{`{{`}} $labels.pod {{`}}`}})
        description: "ProxySQL instance is down on {{`{{`}} $labels.pod {{`}}`}}\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{ end -}}
    {{ $proxysqlServiceDown := index (default dict .rules) "proxysqlServiceDown" }}
    {{ if (and $proxysqlServiceDown (include "proxysql-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $proxysqlServiceDown.enabled $proxysqlServiceDown.severity))) -}}
    - alert: ProxySQLServiceDown
      expr: sum by (service) (proxysql_uptime_seconds_total{job="{{ $app }}-stats",namespace="{{ $.Release.Namespace }}"}) == 0
      for: {{ $proxysqlServiceDown.duration }}
      labels:
        severity: {{ $proxysqlServiceDown.severity }}
        {{- include "proxysql-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: ProxySQL service down (instance {{`{{`}} $labels.pod {{`}}`}})
        description: "ProxySQL service is down on {{`{{`}} $labels.pod {{`}}`}}\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{ end -}}
    {{ $proxysqlTooManyConnections := index (default dict .rules) "proxysqlTooManyConnections" }}
    {{ if (and $proxysqlTooManyConnections (include "proxysql-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $proxysqlTooManyConnections.enabled $proxysqlTooManyConnections.severity))) -}}
    - alert: ProxySQLTooManyConnections
      expr: max_over_time(proxysql_client_connections_connected{job="{{ $app }}-stats",namespace="{{ $.Release.Namespace }}"}[1m]) / proxysql_mysql_max_connections{job="{{ $app }}-stats",namespace="{{ $.Release.Namespace }}"} * 100 > {{$proxysqlTooManyConnections.val}}
      for: {{ $proxysqlTooManyConnections.duration }}
      labels:
        severity: {{ $proxysqlTooManyConnections.severity }}
        {{- include "proxysql-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: ProxySQL too many connections (> {{$proxysqlTooManyConnections.val}}%) (instance {{`{{`}} $labels.pod {{`}}`}})
        description: "More than {{$proxysqlTooManyConnections.val}}% of ProxySQL connections are in use on {{`{{`}} $labels.pod {{`}}`}}\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{ end -}}
    {{ $proxysqlSlowQueries := index (default dict .rules) "proxysqlSlowQueries" }}
    {{ if (and $proxysqlSlowQueries (include "proxysql-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $proxysqlSlowQueries.enabled $proxysqlSlowQueries.severity))) -}}
    - alert: ProxySQLSlowQueries
      expr: increase(proxysql_slow_queries_total{job="{{ $app }}-stats",namespace="{{ $.Release.Namespace }}"}[1m]) > 0
      for: {{ $proxysqlSlowQueries.duration }}
      labels:
        severity: {{ $proxysqlSlowQueries.severity }}
        {{- include "proxysql-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: ProxySQL slow queries on (instance {{`{{`}} $labels.pod {{`}}`}})
        description: "ProxySQL server mysql has some new slow query.\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{ end -}}
    {{ $proxysqlRestarted := index (default dict .rules) "proxysqlRestarted" }}
    {{ if (and $proxysqlRestarted (include "proxysql-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $proxysqlRestarted.enabled $proxysqlRestarted.severity))) -}}
    - alert: ProxySQLRestarted
      expr: proxysql_uptime_seconds_total{job="{{ $app }}-stats",namespace="{{ $.Release.Namespace }}"} < {{$proxysqlRestarted.val}}
      for: {{ $proxysqlRestarted.duration }}
      labels:
        severity: {{ $proxysqlRestarted.severity }}
        {{- include "proxysql-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: ProxySQL restarted ({{$proxysqlRestarted.val}} second ago) (instance {{`{{`}} $labels.pod {{`}}`}})
        description: "ProxySQL restarted\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{ end -}}
    {{ $proxysqlHighIncomingBytes := index (default dict .rules) "proxysqlHighIncomingBytes" }}
    {{ if (and $proxysqlHighIncomingBytes (include "proxysql-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $proxysqlHighIncomingBytes.enabled $proxysqlHighIncomingBytes.severity))) -}}
    - alert: ProxySQLHighIncomingBytes
      expr: rate(proxysql_queries_frontends_bytes_total{job="{{ $app }}-stats",namespace="{{ $.Release.Namespace }}",traffic_flow="received"}[1m]) > {{$proxysqlHighIncomingBytes.val}}
      for: {{ $proxysqlHighIncomingBytes.duration }}
      labels:
        severity: {{ $proxysqlHighIncomingBytes.severity }}
        {{- include "proxysql-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: ProxySQL has high incoming bytes second (> {{$proxysqlHighIncomingBytes.val}}) (instance {{`{{`}} $labels.pod {{`}}`}})
        description: "ProxySQL has high incoming bytes per second on (instance {{`{{`}} $labels.pod {{`}}`}})\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{ end -}}
    {{ $proxysqlHighOutgoingBytes := index (default dict .rules) "proxysqlHighOutgoingBytes" }}
    {{ if (and $proxysqlHighOutgoingBytes (include "proxysql-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $proxysqlHighOutgoingBytes.enabled $proxysqlHighOutgoingBytes.severity))) -}}
    - alert: ProxySQLHighOutgoingBytes
      expr: rate(proxysql_queries_frontends_bytes_total{job="{{ $app }}-stats",namespace="{{ $.Release.Namespace }}",traffic_flow="sent"}[1m]) > {{$proxysqlHighOutgoingBytes.val}}
      for: {{ $proxysqlHighOutgoingBytes.duration }}
      labels:
        severity: {{ $proxysqlHighOutgoingBytes.severity }}
        {{- include "proxysql-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: ProxySQL has high outgoing bytes second (> {{$proxysqlHighOutgoingBytes.val}}) (instance {{`{{`}} $labels.pod {{`}}`}})
        description: "ProxySQL has high outgoing bytes per second on (instance {{`{{`}} $labels.pod {{`}}`}})\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{ end -}}
  {{ end -}}
  {{ end -}}


  {{ with .Values.form.alert.groups.cluster -}}
  {{ if (include "proxysql-alerts.alertGroupEnabled" (list $.Values.form.alert.enabled .)) -}}
  - name: proxysql.cluster.{{ $.Release.Namespace }}.{{ $app }}.rules
    rules:
    {{ $proxysqlClusterSyncFailure := index (default dict .rules) "proxysqlClusterSyncFailure" }}
    {{ if (and $proxysqlClusterSyncFailure (include "proxysql-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $proxysqlClusterSyncFailure.enabled $proxysqlClusterSyncFailure.severity))) -}}
    - alert: ProxySQLCLusterSyncFailure
      expr: sum by(job) (rate(proxysql_cluster_syn_conflict_total{job="{{ $app }}-stats",namespace="{{ $.Release.Namespace }}"}[1m])) > {{$proxysqlClusterSyncFailure.val}}
      for: {{ $proxysqlClusterSyncFailure.duration }}
      labels:
        severity: {{ $proxysqlClusterSyncFailure.severity }}
        {{- include "proxysql-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: ProxySQL Cluster Sync Failed ( > {{$proxysqlClusterSyncFailure.val}} second,) (instance {{`{{`}} $labels.pod {{`}}`}})
        description: "ProxySQL Cluster Sync Failed for {{`{{`}} $labels.pod {{`}}`}}\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
  {{ end -}}
  {{ end -}}


  {{ with .Values.form.alert.groups.provisioner -}}
  {{ if (include "proxysql-alerts.alertGroupEnabled" (list $.Values.form.alert.enabled .)) -}}
  - name: proxysql.provisioner.{{ $.Release.Namespace }}.{{ $app }}.rules
    rules:
    {{ $appPhaseNotReady := index (default dict .rules) "appPhaseNotReady" }}
    {{ if (and $appPhaseNotReady (include "proxysql-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $appPhaseNotReady.enabled $appPhaseNotReady.severity))) -}}
    - alert: KubeDBProxySQLPhaseNotReady
      expr: kubedb_com_proxysql_status_phase{phase="NotReady",app="{{ $app }}",namespace="{{ $.Release.Namespace }}"} == 1
      for: {{ $appPhaseNotReady.duration }}
      labels:
        severity: {{ $appPhaseNotReady.severity }}
        {{- include "proxysql-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: KubeDB ProxySQL Phase NotReady (proxysql {{`{{`}} $labels.proxysql {{`}}`}})
        description: "KubeDB ProxySQL Phase not ready on {{`{{`}} $labels.proxysql {{`}}`}}\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{ end -}}
    {{ $appPhaseCritical := index (default dict .rules) "appPhaseCritical" }}
    {{ if (and $appPhaseCritical (include "proxysql-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $appPhaseCritical.enabled $appPhaseCritical.severity))) -}}
    - alert: KubeDBProxySQLPhaseCritical
      expr: kubedb_com_proxysql_status_phase{phase="Critical",app="{{ $app }}",namespace="{{ $.Release.Namespace }}"} == 1
      for: {{ $appPhaseCritical.duration }}
      labels:
        severity: {{ $appPhaseCritical.severity }}
        {{- include "proxysql-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: KubeDB ProxySQL Phase Critical (proxysql {{`{{`}} $labels.proxysql {{`}}`}})
        description: "KubeDB ProxySQL Phase Critical {{`{{`}} $labels.proxysql {{`}}`}}\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
  {{ end -}}
  {{ end -}}


  {{ with .Values.form.alert.groups.opsManager -}}
  {{ if (include "proxysql-alerts.alertGroupEnabled" (list $.Values.form.alert.enabled .)) -}}
  - name: proxysql.opsManager.{{ $.Release.Namespace }}.{{ $app }}.rules
    rules:
    {{ $opsRequestOnProgress := index (default dict .rules) "opsRequestOnProgress" }}
    {{ if (and $opsRequestOnProgress (include "proxysql-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $opsRequestOnProgress.enabled $opsRequestOnProgress.severity))) -}}
    - alert: KubeDBProxySQLOpsRequestOnProgress
      expr: ops_kubedb_com_proxysqlopsrequest_status_phase{phase="Progressing",app="{{ $app }}",namespace="{{ $.Release.Namespace }}"} == 1
      for: {{ $opsRequestOnProgress.duration }}
      labels:
        severity: {{ $opsRequestOnProgress.severity }}
        {{- include "proxysql-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: ProxySQLOpsRequest on progress (proxysqlopsrequest {{`{{`}} $labels.proxysqlopsrequest {{`}}`}})
        description: "ProxySQLOpsRequest {{`{{`}} $labels.proxysqlopsrequest {{`}}`}} is in progressressing status\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{ end -}}
    {{ $opsRequestStatusProgressingToLong := index (default dict .rules) "opsRequestStatusProgressingToLong" }}
    {{ if (and $opsRequestStatusProgressingToLong (include "proxysql-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $opsRequestStatusProgressingToLong.enabled $opsRequestStatusProgressingToLong.severity))) -}}
    - alert: KubeDBProxySQLOpsRequestStatusProgressingToLong
      expr: ops_kubedb_com_proxysqlopsrequest_status_phase{phase="Progressing",app="{{ $app }}",namespace="{{ $.Release.Namespace }}"} == 1
      for: {{ $opsRequestStatusProgressingToLong.duration }}
      labels:
        severity: {{ $opsRequestStatusProgressingToLong.severity }}
        {{- include "proxysql-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: ProxySQLOpsRequest is in progressing status for too long (proxysqlopsrequest {{`{{`}} $labels.proxysqlopsrequest {{`}}`}})
        description: "ProxySQLOpsRequest {{`{{`}} $labels.proxysqlopsrequest {{`}}`}} is in progressing status for too long\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{ end -}}
    {{ $opsRequestFailed := index (default dict .rules) "opsRequestFailed" }}
    {{ if (and $opsRequestFailed (include "proxysql-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $opsRequestFailed.enabled $opsRequestFailed.severity))) -}}
    - alert: KubeDBProxySQLOpsRequestFailed
      expr: ops_kubedb_com_proxysqlopsrequest_status_phase{phase="Failed",app="{{ $app }}",namespace="{{ $.Release.Namespace }}"} == 1
      for: {{ $opsRequestFailed.duration }}
      labels:
        severity: {{ $opsRequestFailed.severity }}
        {{- include "proxysql-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: ProxySQLOpsRequest failed (proxysqlopsrequest {{`{{`}} $labels.proxysqlopsrequest {{`}}`}})
        description: "ProxySQLOpsRequest {{`{{`}} $labels.proxysqlopsrequest {{`}}`}} failed \n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
  {{ end -}}
  {{ end -}}

{{ end }}
