{{ $app := (include "hanadb-alerts.fullname" .) }}

{{ if (include "hanadb-alerts.alertsEnabled" .Values.form.alert.enabled) }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ $app }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "hanadb-alerts.labels" . | nindent 4 }}
{{- if .Values.form.alert.labels }}
    {{- toYaml .Values.form.alert.labels | nindent 4 }}
{{- end }}
{{- if .Values.form.alert.annotations }}
  annotations:
    {{- toYaml .Values.form.alert.annotations | nindent 4 }}
{{- end }}
spec:
  groups:
  {{ with .Values.form.alert.groups.database -}}
  {{ if (include "hanadb-alerts.alertGroupEnabled" (list $.Values.form.alert.enabled .)) -}}
  - name: hanadb.database.{{ $.Release.Namespace }}.{{ $app }}.rules
    rules:
    {{ $hanadbInstanceDown := index (default dict .rules) "hanadbInstanceDown" }}
    {{ if (and $hanadbInstanceDown (include "hanadb-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $hanadbInstanceDown.enabled $hanadbInstanceDown.severity))) -}}
    - alert: HanaDBInstanceDown
      expr: up{job="{{- $app -}}-stats",namespace="{{ $.Release.Namespace }}"} == 0
      for: {{ $hanadbInstanceDown.duration }}
      labels:
        severity: {{ $hanadbInstanceDown.severity }}
        {{- include "hanadb-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: HanaDB instance down (instance {{`{{`}} $labels.pod {{`}}`}})
        description: "HanaDB instance is down on {{`{{`}} $labels.pod {{`}}`}}\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
    {{ $hanadbServiceDown := index (default dict .rules) "hanadbServiceDown" }}
    {{ if (and $hanadbServiceDown (include "hanadb-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $hanadbServiceDown.enabled $hanadbServiceDown.severity))) -}}
    - alert: HanaDBServiceDown
      expr: sum by (service) (up{job="{{ $app }}-stats",namespace="{{ $.Release.Namespace }}"}) == 0
      for: {{ $hanadbServiceDown.duration }}
      labels:
        severity: {{ $hanadbServiceDown.severity }}
        {{- include "hanadb-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: HanaDB service down
        description: "All HanaDB scrape targets are down\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
    {{ $hanadbRestarted := index (default dict .rules) "hanadbRestarted" }}
    {{ if (and $hanadbRestarted (include "hanadb-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $hanadbRestarted.enabled $hanadbRestarted.severity))) -}}
    - alert: HanaDBRestarted
      expr: (time() - min(kube_pod_start_time{namespace="{{ $.Release.Namespace }}", pod=~"{{ $.Release.Name }}(-arbiter)?-.+"})) < {{ $hanadbRestarted.val }}
      for: {{ $hanadbRestarted.duration }}
      labels:
        severity: {{ $hanadbRestarted.severity }}
        {{- include "hanadb-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: HanaDB recently restarted (instance {{`{{`}} $labels.pod {{`}}`}})
        description: "HanaDB pod {{`{{`}} $labels.pod {{`}}`}} restarted recently.\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
    {{ $hanadbHighCPUUsage := index (default dict .rules) "hanadbHighCPUUsage" }}
    {{ if (and $hanadbHighCPUUsage (include "hanadb-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $hanadbHighCPUUsage.enabled $hanadbHighCPUUsage.severity))) -}}
    - alert: HanaDBHighCPUUsage
      expr: avg by (pod) (hanadb_cpu_busy_percent{job="{{ $app }}-stats",namespace="{{ $.Release.Namespace }}"}) > {{ $hanadbHighCPUUsage.val }}
      for: {{ $hanadbHighCPUUsage.duration }}
      labels:
        severity: {{ $hanadbHighCPUUsage.severity }}
        {{- include "hanadb-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: HanaDB CPU usage high (instance {{`{{`}} $labels.pod {{`}}`}})
        description: "HanaDB CPU busy percentage is above {{ $hanadbHighCPUUsage.val }} percent.\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
    {{ $hanadbHighMemoryUsage := index (default dict .rules) "hanadbHighMemoryUsage" }}
    {{ if (and $hanadbHighMemoryUsage (include "hanadb-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $hanadbHighMemoryUsage.enabled $hanadbHighMemoryUsage.severity))) -}}
    - alert: HanaDBHighMemoryUsage
      expr: |
        100 * (
          sum by (pod) (
            hanadb_host_memory_used_total_mb{job="{{ $app }}-stats",namespace="{{ $.Release.Namespace }}"}
          )
          /
          clamp_min(
            sum by (pod) (
              hanadb_host_memory_alloc_limit_mb{job="{{ $app }}-stats",namespace="{{ $.Release.Namespace }}"}
            ),
            1
          )
        ) > {{ $hanadbHighMemoryUsage.val }}
      for: {{ $hanadbHighMemoryUsage.duration }}
      labels:
        severity: {{ $hanadbHighMemoryUsage.severity }}
        {{- include "hanadb-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: HanaDB memory usage high (instance {{`{{`}} $labels.pod {{`}}`}})
        description: "HanaDB memory usage is above {{ $hanadbHighMemoryUsage.val }} percent of allocation limit.\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
    {{ $hanadbReplicationNotActive := index (default dict .rules) "hanadbReplicationNotActive" }}
    {{ if (and $hanadbReplicationNotActive (include "hanadb-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $hanadbReplicationNotActive.enabled $hanadbReplicationNotActive.severity))) -}}
    - alert: HanaDBReplicationNotActive
      expr: max by (pod) (hanadb_sr_replication_status{job="{{ $app }}-stats",namespace="{{ $.Release.Namespace }}"}) > 0
      for: {{ $hanadbReplicationNotActive.duration }}
      labels:
        severity: {{ $hanadbReplicationNotActive.severity }}
        {{- include "hanadb-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: HanaDB replication is not active (instance {{`{{`}} $labels.pod {{`}}`}})
        description: "HanaDB system replication status is not ACTIVE.\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
    {{ $diskUsageHigh := index (default dict .rules) "diskUsageHigh" }}
    {{ if (and $diskUsageHigh (include "hanadb-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $diskUsageHigh.enabled $diskUsageHigh.severity))) -}}
    - alert: DiskUsageHigh
      expr: |
        100 * (
          (
            kubelet_volume_stats_used_bytes{job="kubelet", namespace=~"{{ $.Release.Namespace }}"}
            /
            on(namespace, persistentvolumeclaim)
            kubelet_volume_stats_capacity_bytes{job="kubelet", namespace=~"{{ $.Release.Namespace }}"}
          )
          *
          on(namespace, persistentvolumeclaim) group_left(pod)
          max by(namespace, persistentvolumeclaim, pod) (
            kube_pod_spec_volumes_persistentvolumeclaims_info{
              pod=~"{{ $.Release.Name }}(-arbiter)?-.+$",
              namespace=~"{{ $.Release.Namespace }}"
            }
          )
        ) > {{ $diskUsageHigh.val }}
      for: {{ $diskUsageHigh.duration }}
      labels:
        severity: {{ $diskUsageHigh.severity }}
        {{- include "hanadb-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: Persistent volume usage is high
        description: "Persistent volume usage is above {{ $diskUsageHigh.val }}%\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
    {{ $diskAlmostFull := index (default dict .rules) "diskAlmostFull" }}
    {{ if (and $diskAlmostFull (include "hanadb-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $diskAlmostFull.enabled $diskAlmostFull.severity))) -}}
    - alert: DiskAlmostFull
      expr: |
        100 * (
          (
            kubelet_volume_stats_used_bytes{job="kubelet", namespace=~"{{ $.Release.Namespace }}"}
            /
            on(namespace, persistentvolumeclaim)
            kubelet_volume_stats_capacity_bytes{job="kubelet", namespace=~"{{ $.Release.Namespace }}"}
          )
          *
          on(namespace, persistentvolumeclaim) group_left(pod)
          max by(namespace, persistentvolumeclaim, pod) (
            kube_pod_spec_volumes_persistentvolumeclaims_info{
              pod=~"{{ $.Release.Name }}(-arbiter)?-.+$",
              namespace=~"{{ $.Release.Namespace }}"
            }
          )
        ) > {{ $diskAlmostFull.val }}
      for: {{ $diskAlmostFull.duration }}
      labels:
        severity: {{ $diskAlmostFull.severity }}
        {{- include "hanadb-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: Persistent volume is almost full
        description: "Persistent volume usage is above {{ $diskAlmostFull.val }}%\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
  {{ end -}}
  {{ end -}}

  {{ with .Values.form.alert.groups.provisioner -}}
  {{ if (include "hanadb-alerts.alertGroupEnabled" (list $.Values.form.alert.enabled .)) -}}
  - name: hanadb.provisioner.{{ $.Release.Namespace }}.{{ $app }}.rules
    rules:
    {{ $appPhaseNotReady := index (default dict .rules) "appPhaseNotReady" }}
    {{ if (and $appPhaseNotReady (include "hanadb-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $appPhaseNotReady.enabled $appPhaseNotReady.severity))) -}}
    - alert: KubeDBHanaDBPhaseNotReady
      expr: kubedb_com_hanadb_status_phase{phase="NotReady",app="{{ $app }}",namespace="{{ $.Release.Namespace }}"} == 1
      for: {{ $appPhaseNotReady.duration }}
      labels:
        severity: {{ $appPhaseNotReady.severity }}
        {{- include "hanadb-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: KubeDB HanaDB Phase NotReady (hanadb {{`{{`}} $labels.app {{`}}`}})
        description: "KubeDB HanaDB phase is NotReady\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
    {{ $appPhaseCritical := index (default dict .rules) "appPhaseCritical" }}
    {{ if (and $appPhaseCritical (include "hanadb-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $appPhaseCritical.enabled $appPhaseCritical.severity))) -}}
    - alert: KubeDBHanaDBPhaseCritical
      expr: kubedb_com_hanadb_status_phase{phase="Critical",app="{{ $app }}",namespace="{{ $.Release.Namespace }}"} == 1
      for: {{ $appPhaseCritical.duration }}
      labels:
        severity: {{ $appPhaseCritical.severity }}
        {{- include "hanadb-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: KubeDB HanaDB Phase Critical (hanadb {{`{{`}} $labels.app {{`}}`}})
        description: "KubeDB HanaDB phase is Critical\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
  {{ end -}}
  {{ end -}}
{{ end }}
