{{ $app := (include "kafka-alerts.fullname" .) }}

{{ if (include "kafka-alerts.alertsEnabled" .Values.form.alert.enabled) }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ $app }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "kafka-alerts.labels" . | nindent 4 }}
{{- if .Values.form.alert.labels }}
    {{- toYaml .Values.form.alert.labels | nindent 4 }}
{{- end }}
{{- if .Values.form.alert.annotations }}
  annotations:
    {{- toYaml .Values.form.alert.annotations | nindent 4 }}
{{- end }}
spec:
  groups:
  {{ with .Values.form.alert.groups.database -}}
  {{ if (include "kafka-alerts.alertGroupEnabled" (list $.Values.form.alert.enabled .)) -}}
  - name: kafka.database.{{ $.Release.Namespace }}.{{ $app }}.rules
    rules:
    {{ $kafkaUnderReplicatedPartitions := index (default dict .rules) "kafkaUnderReplicatedPartitions" }}
    {{ if (and $kafkaUnderReplicatedPartitions (include "kafka-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $kafkaUnderReplicatedPartitions.enabled $kafkaUnderReplicatedPartitions.severity))) -}}
    - alert: KafkaUnderReplicatedPartitions
      expr: kafka_server_replicamanager_underreplicatedpartitions{job="{{ $app }}-stats",namespace="{{ $.Release.Namespace }}"} > {{ $kafkaUnderReplicatedPartitions.val }}
      for: {{ $kafkaUnderReplicatedPartitions.duration }}
      labels:
        severity: {{ $kafkaUnderReplicatedPartitions.severity }}
        {{- include "kafka-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: Kafka under replicated partitions (instance {{`{{`}} $labels.instance {{`}}`}})
        description: "There are {{`{{`}} $value {{`}}`}} under replicated partitions.\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
    {{ $kafkaAbnormalControllerState := index (default dict .rules) "kafkaAbnormalControllerState" }}
    {{ if (and $kafkaAbnormalControllerState (include "kafka-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $kafkaAbnormalControllerState.enabled $kafkaAbnormalControllerState.severity))) -}}
    - alert: KafkaAbnormalControllerState
      expr: sum(kafka_controller_kafkacontroller_activecontrollercount{job="{{ $app }}-stats",namespace="{{ $.Release.Namespace }}"}) != {{ $kafkaAbnormalControllerState.val }}
      for: {{ $kafkaAbnormalControllerState.duration }}
      labels:
        severity: {{ $kafkaAbnormalControllerState.severity }}
        {{- include "kafka-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: At least one active controller must be acting (instance {{`{{`}} $labels.instance {{`}}`}})
        description: "There are {{`{{`}} $value {{`}}`}} active controllers.\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
    {{ $kafkaOfflinePartitions := index (default dict .rules) "kafkaOfflinePartitions" }}
    {{ if (and $kafkaOfflinePartitions (include "kafka-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $kafkaOfflinePartitions.enabled $kafkaOfflinePartitions.severity))) -}}
    - alert: KafkaOfflinePartitions
      expr: sum(kafka_controller_kafkacontroller_offlinepartitionscount{job="{{ $app }}-stats",namespace="{{ $.Release.Namespace }}"}) > {{ $kafkaOfflinePartitions.val }}
      for: {{ $kafkaOfflinePartitions.duration }}
      labels:
        severity: {{ $kafkaOfflinePartitions.severity }}
        {{- include "kafka-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: Kafka offline partitions (instance {{`{{`}} $labels.instance {{`}}`}})
        description: "One or more partitions have no leader.\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
    {{ $kafkaUnderMinIsrPartitionCount := index (default dict .rules) "kafkaUnderMinIsrPartitionCount" }}
    {{ if (and $kafkaUnderMinIsrPartitionCount (include "kafka-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $kafkaUnderMinIsrPartitionCount.enabled $kafkaUnderMinIsrPartitionCount.severity))) -}}
    - alert: KafkaUnderMinIsrPartitionCount
      expr: kafka_server_replicamanager_underminisrpartitioncount{job="{{ $app }}-stats",namespace="{{ $.Release.Namespace }}"} > {{ $kafkaUnderMinIsrPartitionCount.val }}
      for: {{ $kafkaUnderMinIsrPartitionCount.duration }}
      labels:
        severity: {{ $kafkaUnderMinIsrPartitionCount.severity }}
        {{- include "kafka-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: Kafka under min ISR partitions (instance {{`{{`}} $labels.instance {{`}}`}})
        description: "There are {{`{{`}} $value {{`}}`}} partitions under the min ISR.\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
    {{ $kafkaOfflineLogDirectoryCount := index (default dict .rules) "kafkaOfflineLogDirectoryCount" }}
    {{ if (and $kafkaOfflineLogDirectoryCount (include "kafka-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $kafkaOfflineLogDirectoryCount.enabled $kafkaOfflineLogDirectoryCount.severity))) -}}
    - alert: KafkaOfflineLogDirectoryCount
      expr: kafka_log_logmanager_offlinelogdirectorycount{job="{{ $app }}-stats",namespace="{{ $.Release.Namespace }}"} > {{ $kafkaOfflineLogDirectoryCount.val }}
      for: {{ $kafkaOfflineLogDirectoryCount.duration }}
      labels:
        severity: {{ $kafkaOfflineLogDirectoryCount.severity }}
        {{- include "kafka-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: Kafka offline log directories (instance {{`{{`}} $labels.instance {{`}}`}})
        description: "There are {{`{{`}} $value {{`}}`}} offline log directories.\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
    {{ $kafkaISRExpandRate := index (default dict .rules) "kafkaISRExpandRate" }}
    {{ if (and $kafkaISRExpandRate (include "kafka-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $kafkaISRExpandRate.enabled $kafkaISRExpandRate.severity))) -}}
    - alert: KafkaISRExpandRate
      expr: sum(irate(kafka_server_replicamanager_isrexpands_total{job="{{ $app }}-stats",namespace="{{ $.Release.Namespace }}"}[5m])) by (service) != {{ $kafkaISRExpandRate.val }}
      for: {{ $kafkaISRExpandRate.duration }}
      labels:
        severity: {{ $kafkaISRExpandRate.severity }}
        {{- include "kafka-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: Kafka ISR Expansion Rate (instance {{`{{`}} $labels.instance {{`}}`}})
        description: "If a broker goes down, ISR for some of the partitions shrink. When that broker is up again, ISRs are expanded once the replicas are fully caught up. Other than that, the expected value for ISR expansion rate is 0. If ISR is expanding and shrinking frequently, adjust Allowed replica lag..\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
    {{ $kafkaISRShrinkRate := index (default dict .rules) "kafkaISRShrinkRate" }}
    {{ if (and $kafkaISRShrinkRate (include "kafka-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $kafkaISRShrinkRate.enabled $kafkaISRShrinkRate.severity))) -}}
    - alert: KafkaISRShrinkRate
      expr: sum(irate(kafka_server_replicamanager_isrshrinks_total{job="{{ $app }}-stats",namespace="{{ $.Release.Namespace }}"}[5m])) by (service) != {{ $kafkaISRShrinkRate.val }}
      for: {{ $kafkaISRShrinkRate.duration }}
      labels:
        severity: {{ $kafkaISRShrinkRate.severity }}
        {{- include "kafka-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: Kafka ISR Shrink Rate (instance {{`{{`}} $labels.instance {{`}}`}})
        description: "If a broker goes down, ISR for some of the partitions shrink. When that broker is up again, ISRs are expanded once the replicas are fully caught up. Other than that, the expected value for ISR shrink rate is 0. If ISR is expanding and shrinking frequently, adjust Allowed replica lag.\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
    {{ $kafkaBrokerCount := index (default dict .rules) "kafkaBrokerCount" }}
    {{ if (and $kafkaBrokerCount (include "kafka-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $kafkaBrokerCount.enabled $kafkaBrokerCount.severity))) -}}
    - alert: KafkaBrokerCount
      expr: count(kafka_server_kafkaserver_brokerstate{job="{{ $app }}-stats",namespace="{{ $.Release.Namespace }}"}) == {{ $kafkaBrokerCount.val }}
      for: {{ $kafkaBrokerCount.duration }}
      labels:
        severity: {{ $kafkaBrokerCount.severity }}
        {{- include "kafka-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: No Kafka Brokers online! (instance {{`{{`}} $labels.instance {{`}}`}})
        description: "Broker count is 0.\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
    {{ $kafkaNetworkProcessorIdlePercent := index (default dict .rules) "kafkaNetworkProcessorIdlePercent" }}
    {{ if (and $kafkaNetworkProcessorIdlePercent (include "kafka-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $kafkaNetworkProcessorIdlePercent.enabled $kafkaNetworkProcessorIdlePercent.severity))) -}}
    - alert: KafkaNetworkProcessorIdlePercent
      expr: avg(sum(kafka_network_processor_idle_percent{job="{{ $app }}-stats",namespace="{{ $.Release.Namespace }}"}) by (networkProcessor)) by (service_name) < {{ $kafkaNetworkProcessorIdlePercent.val }}
      for: {{ $kafkaNetworkProcessorIdlePercent.duration }}
      labels:
        severity: {{ $kafkaNetworkProcessorIdlePercent.severity }}
        {{- include "kafka-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: Kafka Network Processor Idle Percent is {{`{{`}} $value {{`}}`}} (instance {{`{{`}} $labels.instance {{`}}`}})
        description: "The average fraction of time the network processors are idle. A lower value {{`{{`}} $value {{`}}`}} indicates that the network workload of the broker is very high.\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
    {{ $kafkaRequestHandlerIdlePercent := index (default dict .rules) "kafkaRequestHandlerIdlePercent" }}
    {{ if (and $kafkaRequestHandlerIdlePercent (include "kafka-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $kafkaRequestHandlerIdlePercent.enabled $kafkaRequestHandlerIdlePercent.severity))) -}}
    - alert: KafkaRequestHandlerIdlePercent
      expr: avg(sum(kafka_network_processor_idle_percent{job="{{ $app }}-stats",namespace="{{ $.Release.Namespace }}"}) by (networkProcessor)) by (service_name) < {{ $kafkaRequestHandlerIdlePercent.val }}
      for: {{ $kafkaRequestHandlerIdlePercent.duration }}
      labels:
        severity: {{ $kafkaRequestHandlerIdlePercent.severity }}
        {{- include "kafka-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: Kafka Request Handler Idle Percent is {{`{{`}} $value {{`}}`}} (instance {{`{{`}} $labels.instance {{`}}`}})
        description: "The average fraction of time the request handler threads (IO) are idle. A lower value indicates that the workload of a broker is very high.\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
    {{ $kafkaReplicaFetcherManagerMaxLag := index (default dict .rules) "kafkaReplicaFetcherManagerMaxLag" }}
    {{ if (and $kafkaReplicaFetcherManagerMaxLag (include "kafka-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $kafkaReplicaFetcherManagerMaxLag.enabled $kafkaReplicaFetcherManagerMaxLag.severity))) -}}
    - alert: KafkaReplicaFetcherManagerMaxLag
      expr: avg(kafka_server_replicafetchermanager_maxlag{job="{{ $app }}-stats",namespace="{{ $.Release.Namespace }}"}) by (service) > {{ $kafkaReplicaFetcherManagerMaxLag.val }}
      for: {{ $kafkaReplicaFetcherManagerMaxLag.duration }}
      labels:
        severity: {{ $kafkaReplicaFetcherManagerMaxLag.severity }}
        {{- include "kafka-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: Replica Fetcher Manager Max Lag is {{`{{`}} $value {{`}}`}} (instance {{`{{`}} $labels.instance {{`}}`}})
        description: "The maximum lag between the time that messages are received by the leader replica and by the follower replicas.\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
    {{ $kafkaTopicCount := index (default dict .rules) "kafkaTopicCount" }}
    {{ if (and $kafkaTopicCount (include "kafka-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $kafkaTopicCount.enabled $kafkaTopicCount.severity))) -}}
    - alert: KafkaTopicCount
      expr: count(count(kafka_server_brokertopicmetrics_messagesin_total{job="{{ $app }}-stats",namespace="{{ $.Release.Namespace }}"}) by (topic,service)) by (service) > {{ $kafkaTopicCount.val }}
      for: {{ $kafkaTopicCount.duration }}
      labels:
        severity: {{ $kafkaTopicCount.severity }}
        {{- include "kafka-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: Kafka 1000 topics reached (instance {{`{{`}} $labels.instance {{`}}`}})
        description: "The number of active topics in the cluster has reached 1000.\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}


    {{ $kafkaPhaseCritical := index (default dict .rules) "kafkaPhaseCritical" }}
    {{ if (and $kafkaPhaseCritical (include "kafka-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $kafkaPhaseCritical.enabled $kafkaPhaseCritical.severity))) -}}
    - alert: KafkaPhaseCritical
      expr: kubedb_com_kafka_status_phase{app="{{ $app }}", namespace="{{ $.Release.Namespace }}",phase="Critical"} >= 1
      for: {{ $kafkaPhaseCritical.duration }}
      labels:
        severity: {{ $kafkaPhaseCritical.severity }}
        {{- include "kafka-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: Kafka database is in Critical state (instance {{`{{`}} $labels.instance {{`}}`}})
        description: "Database in Critical state, one or more database nodes are not working properly.\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
    {{ $kafkaDown := index (default dict .rules) "kafkaDown" }}
    {{ if (and $kafkaDown (include "kafka-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $kafkaDown.enabled $kafkaDown.severity))) -}}
    - alert: KafkaDown
      expr: kubedb_com_kafka_status_phase{app="{{ $app }}", namespace="{{ $.Release.Namespace }}",phase="NotReady"} >= 1
      for: {{ $kafkaDown.duration }}
      labels:
        severity: {{ $kafkaDown.severity }}
        {{- include "kafka-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: Kafka database is in NotReady state (instance {{`{{`}} $labels.instance {{`}}`}})
        description: "Database in NotReady state, database read/write is failing.\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
    
    {{ $diskUsageHigh := index (default dict .rules) "diskUsageHigh" }}
    {{ if (and $diskUsageHigh (include "kafka-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $diskUsageHigh.enabled $diskUsageHigh.severity))) -}}
    - alert: DiskUsageHigh
      expr: (kubelet_volume_stats_used_bytes{service="kubernetes"} / on(persistentvolumeclaim) group_left(pod) ((kubelet_volume_stats_used_bytes{service="kubernetes"} + on(persistentvolumeclaim) group_left(pod) kube_pod_spec_volumes_persistentvolumeclaims_info{pod=~"{{ $.Release.Name }}-.+$",namespace=~"{{ $.Release.Namespace }}"}) ) )
        * 100 > {{ $diskUsageHigh.val }}
      for: {{ $diskUsageHigh.duration }}
      labels:
        severity: {{ $diskUsageHigh.severity }}
        {{- include "kafka-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: Persistent Volume Usages in instance {{`{{`}} $labels.instance {{`}}`}}
        description: "Persistent Volume Usages\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
    {{ $diskAlmostFull := index (default dict .rules) "diskAlmostFull" }}
    {{ if (and $diskAlmostFull (include "kafka-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $diskAlmostFull.enabled $diskAlmostFull.severity))) -}}
    - alert: DiskAlmostFull
      expr: (kubelet_volume_stats_used_bytes{service="kubernetes"} / on(persistentvolumeclaim) group_left(pod) ((kubelet_volume_stats_used_bytes{service="kubernetes"} + on(persistentvolumeclaim) group_left(pod) kube_pod_spec_volumes_persistentvolumeclaims_info{pod=~"{{ $.Release.Name }}-.+$",namespace=~"{{ $.Release.Namespace }}"}) ) )
        * 100 > {{ $diskAlmostFull.val }}
      for: {{ $diskAlmostFull.duration }}
      labels:
        severity: {{ $diskAlmostFull.severity }}
        {{- include "kafka-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: Persistent Volume Usages in instance {{`{{`}} $labels.instance {{`}}`}}
        description: "Persistent Volume Usages\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
  {{end -}}
  {{end -}}


  {{ with .Values.form.alert.groups.provisioner -}}
  {{ if (include "kafka-alerts.alertGroupEnabled" (list $.Values.form.alert.enabled .)) -}}
  - name: kafka.provisioner.{{ $.Release.Namespace }}.{{ $app }}.rules
    rules:
    {{ $appPhaseNotReady := index (default dict .rules) "appPhaseNotReady" }}
    {{ if (and $appPhaseNotReady (include "kafka-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $appPhaseNotReady.enabled $appPhaseNotReady.severity))) -}}
    - alert: KubeDBKafkaPhaseNotReady
      expr: kubedb_com_kafka_status_phase{phase="NotReady",app="{{ $app }}",namespace="{{ $.Release.Namespace }}"} == 1
      for: {{ $appPhaseNotReady.duration }}
      labels:
        severity: {{ $appPhaseNotReady.severity }}
        {{- include "kafka-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: KubeDB Kafka Phase NotReady (kafka {{`{{`}} $labels.kafka {{`}}`}})
        description: "KubeDB Kafka Phase not ready on {{`{{`}} $labels.kafka {{`}}`}}\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{ end -}}
    {{ $appPhaseCritical := index (default dict .rules) "appPhaseCritical" }}
    {{ if (and $appPhaseCritical (include "kafka-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $appPhaseCritical.enabled $appPhaseCritical.severity))) -}}
    - alert: KubeDBKafkaPhaseCritical
      expr: kubedb_com_kafka_status_phase{phase="Critical",app="{{ $app }}",namespace="{{ $.Release.Namespace }}"} == 1
      for: {{ $appPhaseCritical.duration }}
      labels:
        severity: {{ $appPhaseCritical.severity }}
        {{- include "kafka-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: KubeDB Kafka Phase Critical (kafka {{`{{`}} $labels.kafka {{`}}`}})
        description: "KubeDB Kafka Phase Critical {{`{{`}} $labels.kafka {{`}}`}}\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
  {{ end -}}
  {{ end -}}


{{ end }}
