{{ $app := (include "zookeeper-alerts.fullname" .) }}

{{ if (include "zookeeper-alerts.alertsEnabled" .Values.form.alert.enabled) }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ $app }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "zookeeper-alerts.labels" . | nindent 4 }}
{{- if .Values.form.alert.labels }}
    {{- toYaml .Values.form.alert.labels | nindent 4 }}
{{- end }}
{{- if .Values.form.alert.annotations }}
  annotations:
    {{- toYaml .Values.form.alert.annotations | nindent 4 }}
{{- end }}
spec:
  groups:
  {{ with .Values.form.alert.groups.database -}}
  {{ if (include "zookeeper-alerts.alertGroupEnabled" (list $.Values.form.alert.enabled .)) -}}
  - name: zookeeper.database.{{ $.Release.Namespace }}.{{ $app }}.rules
    rules:
    {{ $zookeeperDown := index (default dict .rules) "zookeeperDown" }}
    {{ if (and $zookeeperDown (include "zookeeper-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $zookeeperDown.enabled $zookeeperDown.severity))) -}}
    - alert: ZooKeeperDown
      expr: up{job="{{- $app -}}-stats",namespace="{{ $.Release.Namespace }}"} == 0
      for: {{ $zookeeperDown.duration }}
      labels:
        severity: {{ $zookeeperDown.severity }}
        {{- include "zookeeper-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: ZooKeeper instance down (instance {{`{{`}} $labels.pod {{`}}`}})
        description: "ZooKeeper instance is down on {{`{{`}} $labels.pod {{`}}`}}\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{end -}}
    {{ $zookeeperTooManyNodes := index (default dict .rules) "zookeeperTooManyNodes" }}
    {{ if (and $zookeeperTooManyNodes (include "zookeeper-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $zookeeperTooManyNodes.enabled $zookeeperTooManyNodes.severity))) -}}
    - alert: ZooKeeperTooManyNodes
      expr: znode_count{job="{{- $app -}}-stats",namespace="{{ $.Release.Namespace }}"}  > {{$zookeeperTooManyNodes.val}}
      for: {{ $zookeeperTooManyNodes.duration }}
      labels:
        severity: {{ $zookeeperTooManyNodes.severity }}
        {{- include "zookeeper-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: ZooKeeper missing master (instance {{`{{`}} $labels.pod {{`}}`}})
        description: "ZooKeeper ensemble has too many znodes\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{end -}}
    {{ $zookeeperTooManyConnections := index (default dict .rules) "zookeeperTooManyConnections" }}
    {{ if (and $zookeeperTooManyConnections (include "zookeeper-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $zookeeperTooManyConnections.enabled $zookeeperTooManyConnections.severity))) -}}
    - alert: ZooKeeperTooManyConnections
      expr: num_alive_connections{job="{{- $app -}}-stats",namespace="{{ $.Release.Namespace }}"} > {{$zookeeperTooManyConnections.val}}
      for: {{ $zookeeperTooManyConnections.duration }}
      labels:
        severity: {{ $zookeeperTooManyConnections.severity }}
        {{- include "zookeeper-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: ZooKeeper too many connections (instance {{`{{`}} $labels.pod {{`}}`}})
        description: "ZooKeeper instance has too many connections . More than {{$zookeeperTooManyConnections.val}} of ZooKeeper connections are in use on {{`{{`}} $labels.pod {{`}}`}}\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{ end -}}
    {{ $zookeeperTooBigMemory := index (default dict .rules) "zookeeperTooBigMemory" }}
    {{ if (and $zookeeperTooBigMemory (include "zookeeper-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $zookeeperTooBigMemory.enabled $zookeeperTooBigMemory.severity))) -}}
    - alert: ZooKeeperTooBigMemory
      expr: (approximate_data_size{job="{{- $app -}}-stats",namespace="{{ $.Release.Namespace }}"}) /1024 /1024 > {{$zookeeperTooBigMemory.val}} * 1024
      for: {{ $zookeeperTooBigMemory.duration }}
      labels:
        severity: {{ $zookeeperTooBigMemory.severity }}
        {{- include "zookeeper-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: total occupied memory is too big for znode in (instance {{`{{`}} $labels.pod {{`}}`}})
        description: "ZooKeeper ensemble's znode total occupied memory is too big. \n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{ end -}}
    {{ $zookeeperTooManyWatch := index (default dict .rules) "zookeeperTooManyWatch" }}
    {{ if (and $zookeeperTooManyWatch (include "zookeeper-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $zookeeperTooManyWatch.enabled $zookeeperTooManyWatch.severity))) -}}
    - alert: ZooKeeperTooManyWatch
      expr: watch_count{job="{{- $app -}}-stats",namespace="{{ $.Release.Namespace }}"} > {{$zookeeperTooManyWatch.val}}
      for: {{ $zookeeperTooManyWatch.duration }}
      labels:
        severity: {{ $zookeeperTooManyWatch.severity }}
        {{- include "zookeeper-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: Too many watch is set (instance {{`{{`}} $labels.pod {{`}}`}})
        description: "Too many watch is set .\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
    {{ $zookeeperLeaderElection := index (default dict .rules) "zookeeperLeaderElection" }}
    {{ if (and $zookeeperLeaderElection (include "zookeeper-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $zookeeperLeaderElection.enabled $zookeeperLeaderElection.severity))) -}}
    - alert: ZooKeeperLeaderElection
      expr:  increase(election_time_count{job="{{- $app -}}-stats",namespace="{{ $.Release.Namespace }}"}[5m]) > 0
      for: {{ $zookeeperLeaderElection.duration }}
      labels:
        severity: {{ $zookeeperLeaderElection.severity }}
        {{- include "zookeeper-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: A leader election happened (instance {{`{{`}} $labels.pod {{`}}`}})
        description: "A leader election happened.\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
    {{ $zookeeperTooManyOpenFiles := index (default dict .rules) "zookeeperTooManyOpenFiles" }}
    {{ if (and $zookeeperTooManyOpenFiles (include "zookeeper-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $zookeeperTooManyOpenFiles.enabled $zookeeperTooManyOpenFiles.severity))) -}}
    - alert: ZooKeeperTooManyOpenFiles
      expr: open_file_descriptor_count{job="{{- $app -}}-stats",namespace="{{ $.Release.Namespace }}"} > {{$zookeeperTooManyOpenFiles.val}}
      for: {{ $zookeeperTooManyOpenFiles.duration }}
      labels:
        severity: {{ $zookeeperTooManyOpenFiles.severity }}
        {{- include "zookeeper-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: Too many files is open (instance {{`{{`}} $labels.pod {{`}}`}})
        description: "Too many files is open .\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
    {{ $zookeeperTooLongFsyncTime := index (default dict .rules) "zookeeperTooLongFsyncTime" }}
    {{ if (and $zookeeperTooLongFsyncTime (include "zookeeper-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $zookeeperTooLongFsyncTime.enabled $zookeeperTooLongFsyncTime.severity))) -}}
    - alert: ZooKeeperTooLongFsyncTime
      expr: rate(fsynctime_sum{job="{{- $app -}}-stats",namespace="{{ $.Release.Namespace }}"}[1m]) > {{$zookeeperTooLongFsyncTime.val}}
      for: {{ $zookeeperTooLongFsyncTime.duration }}
      labels:
        severity: {{ $zookeeperTooLongFsyncTime.severity }}
        {{- include "zookeeper-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: Too long fsync time (instance {{`{{`}} $labels.pod {{`}}`}})
        description: "Too long fsync time .\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
    {{ $zookeeperTooLongSnapshotTime := index (default dict .rules) "zookeeperTooLongSnapshotTime" }}
    {{ if (and $zookeeperTooLongSnapshotTime (include "zookeeper-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $zookeeperTooLongSnapshotTime.enabled $zookeeperTooLongSnapshotTime.severity))) -}}
    - alert: ZooKeeperTooLongSnapshotTime
      expr: rate(snapshottime_sum{job="{{- $app -}}-stats",namespace="{{ $.Release.Namespace }}"}[5m]) > {{$zookeeperTooLongSnapshotTime.val}}
      for: {{ $zookeeperTooLongSnapshotTime.duration }}
      labels:
        severity: {{ $zookeeperTooLongSnapshotTime.severity }}
        {{- include "zookeeper-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: Time taken for snapshotting is too long (instance {{`{{`}} $labels.pod {{`}}`}})
        description: "Too long snapshot time .\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
    {{ $zookeeperTooHighAvgLatency := index (default dict .rules) "zookeeperTooHighAvgLatency" }}
    {{ if (and $zookeeperTooHighAvgLatency (include "zookeeper-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $zookeeperTooHighAvgLatency.enabled $zookeeperTooHighAvgLatency.severity))) -}}
    - alert: ZooKeeperTooHighAvgLatency
      expr: avg_latency{job="{{- $app -}}-stats",namespace="{{ $.Release.Namespace }}"} > {{$zookeeperTooHighAvgLatency.val}}
      for: {{ $zookeeperTooHighAvgLatency.duration }}
      labels:
        severity: {{ $zookeeperTooHighAvgLatency.severity }}
        {{- include "zookeeper-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: Average Latency is too high (instance {{`{{`}} $labels.pod {{`}}`}})
        description: "Average Latency is too high .\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
    {{ $zookeeperJvmMemoryFilingUp := index (default dict .rules) "zookeeperJvmMemoryFilingUp" }}
    {{ if (and $zookeeperJvmMemoryFilingUp (include "zookeeper-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $zookeeperJvmMemoryFilingUp.enabled $zookeeperJvmMemoryFilingUp.severity))) -}}
    - alert: ZooKeeperJvmMemoryFilingUp
      expr: jvm_memory_bytes_used{job="{{- $app -}}-stats",namespace="{{ $.Release.Namespace }}"} / jvm_memory_bytes_max{area="heap",job="{{- $app -}}-stats",namespace="{{ $.Release.Namespace }}"}  > {{$zookeeperJvmMemoryFilingUp.val}}
      for: {{ $zookeeperJvmMemoryFilingUp.duration }}
      labels:
        severity: {{ $zookeeperJvmMemoryFilingUp.severity }}
        {{- include "zookeeper-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: Jvm memory is filling up (instance {{`{{`}} $labels.pod {{`}}`}})
        description: "Jvm memory is filling up .\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
    
    {{ $diskUsageHigh := index (default dict .rules) "diskUsageHigh" }}
    {{ if (and $diskUsageHigh (include "zookeeper-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $diskUsageHigh.enabled $diskUsageHigh.severity))) -}}
    - alert: DiskUsageHigh
      expr: (kubelet_volume_stats_used_bytes{service="kubernetes"} / on(persistentvolumeclaim) group_left(pod) ((kubelet_volume_stats_used_bytes{service="kubernetes"} + on(persistentvolumeclaim) group_left(pod) kube_pod_spec_volumes_persistentvolumeclaims_info{pod=~"{{ $.Release.Name }}-.+$",namespace=~"{{ $.Release.Namespace }}"}) ) )
        * 100 > {{ $diskUsageHigh.val }}
      for: {{ $diskUsageHigh.duration }}
      labels:
        severity: {{ $diskUsageHigh.severity }}
        {{- include "zookeeper-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: Persistent Volume Usages in instance {{`{{`}} $labels.instance {{`}}`}}
        description: "Persistent Volume Usages\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
    {{ $diskAlmostFull := index (default dict .rules) "diskAlmostFull" }}
    {{ if (and $diskAlmostFull (include "zookeeper-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $diskAlmostFull.enabled $diskAlmostFull.severity))) -}}
    - alert: DiskAlmostFull
      expr: (kubelet_volume_stats_used_bytes{service="kubernetes"} / on(persistentvolumeclaim) group_left(pod) ((kubelet_volume_stats_used_bytes{service="kubernetes"} + on(persistentvolumeclaim) group_left(pod) kube_pod_spec_volumes_persistentvolumeclaims_info{pod=~"{{ $.Release.Name }}-.+$",namespace=~"{{ $.Release.Namespace }}"}) ) )
        * 100 > {{ $diskAlmostFull.val }}
      for: {{ $diskAlmostFull.duration }}
      labels:
        severity: {{ $diskAlmostFull.severity }}
        {{- include "zookeeper-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: Persistent Volume Usages in instance {{`{{`}} $labels.instance {{`}}`}}
        description: "Persistent Volume Usages\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
  {{end -}}
  {{end -}}


  {{ with .Values.form.alert.groups.provisioner -}}
  {{ if (include "zookeeper-alerts.alertGroupEnabled" (list $.Values.form.alert.enabled .)) -}}
  - name: zookeeper.provisioner.{{ $.Release.Namespace }}.{{ $app }}.rules
    rules:
    {{ $appPhaseNotReady := index (default dict .rules) "appPhaseNotReady" }}
    {{ if (and $appPhaseNotReady (include "zookeeper-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $appPhaseNotReady.enabled $appPhaseNotReady.severity))) -}}
    - alert: KubeDBZooKeeperPhaseNotReady
      expr: kubedb_com_zookeeper_status_phase{phase="NotReady",app="{{ $app }}",namespace="{{ $.Release.Namespace }}"} == 1
      for: {{ $appPhaseNotReady.duration }}
      labels:
        severity: {{ $appPhaseNotReady.severity }}
        {{- include "zookeeper-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: KubeDB ZooKeeper Phase NotReady (zookeeper {{`{{`}} $labels.zookeeper {{`}}`}})
        description: "KubeDB ZooKeeper Phase not ready on {{`{{`}} $labels.zookeeper {{`}}`}}\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{ end -}}
    {{ $appPhaseCritical := index (default dict .rules) "appPhaseCritical" }}
    {{ if (and $appPhaseCritical (include "zookeeper-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $appPhaseCritical.enabled $appPhaseCritical.severity))) -}}
    - alert: KubeDBZooKeeperPhaseCritical
      expr: kubedb_com_zookeeper_status_phase{phase="Critical",app="{{ $app }}",namespace="{{ $.Release.Namespace }}"} == 1
      for: {{ $appPhaseCritical.duration }}
      labels:
        severity: {{ $appPhaseCritical.severity }}
        {{- include "zookeeper-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: KubeDB ZooKeeper Phase Critical (zookeeper {{`{{`}} $labels.zookeeper {{`}}`}})
        description: "KubeDB ZooKeeper Phase Critical {{`{{`}} $labels.zookeeper {{`}}`}}\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
  {{ end -}}
  {{ end -}}

{{ end }}
