{{ $app := (include "memcached-alerts.fullname" .) }}

  {{ if (include "memcached-alerts.alertsEnabled" .Values.form.alert.enabled) }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ $app }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "memcached-alerts.labels" . | nindent 4 }}
  {{- if .Values.form.alert.labels }}
  {{- toYaml .Values.form.alert.labels | nindent 4 }}
  {{- end }}
  {{- if .Values.form.alert.annotations }}
annotations:
  {{- toYaml .Values.form.alert.annotations | nindent 4 }}
  {{- end }}
spec:
  groups:
  {{ with .Values.form.alert.groups.database -}}
  {{ if (include "memcached-alerts.alertGroupEnabled" (list $.Values.form.alert.enabled .)) -}}
  - name: memcached.database.{{ $.Release.Namespace }}.{{ $app }}.rules
    rules:
    {{ $memcachedDown := index (default dict .rules) "memcachedDown" }}
    {{ if (and $memcachedDown (include "memcached-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $memcachedDown.enabled $memcachedDown.severity))) -}}
    - alert: MemcachedDown
      expr: memcached_up{job="{{ $app }}-stats",namespace="{{ $.Release.Namespace }}"} == 0
      for: {{ $memcachedDown.duration }}
      labels:
        severity: {{ $memcachedDown.severity }}
        {{- include "memcached-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: Memcached down (instance {{`{{`}} $labels.pod {{`}}`}})
        description: "Memcached is down on {{`{{`}} $labels.pod {{`}}`}}\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
    {{ $memcachedServiceRespawn := index (default dict .rules) "memcachedServiceRespawn" }}
    {{ if (and $memcachedServiceRespawn (include "memcached-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $memcachedServiceRespawn.enabled $memcachedServiceRespawn.severity))) -}}
    - alert: MemcachedServiceRespawn
      expr:  (memcached_uptime_seconds{job="{{ $app }}-stats",namespace="{{ $.Release.Namespace }}"}) < {{$memcachedServiceRespawn.val}}
      for: {{ $memcachedServiceRespawn.duration }}
      labels:
        severity: {{ $memcachedServiceRespawn.severity }}
        {{- include "memcached-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: Memcached service restart (instance {{`{{`}} $labels.pod {{`}}`}})
        description: "Memcached service restart on {{`{{`}} $labels.pod {{`}}`}}\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
    {{ $memcachedConnectionThrottled := index (default dict .rules) "memcachedConnectionThrottled" }}
    {{ if (and $memcachedConnectionThrottled (include "memcached-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $memcachedConnectionThrottled.enabled $memcachedConnectionThrottled.severity))) -}}
    - alert: MemcachedConnectionThrottled
      expr: increase(memcached_connections_yielded_total{job="{{ $app }}-stats",namespace="{{ $.Release.Namespace }}"}[1m]) > {{$memcachedConnectionThrottled.val}}
      for: {{ $memcachedConnectionThrottled.duration }}
      labels:
        severity: {{ $memcachedConnectionThrottled.severity }}
        {{- include "memcached-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: Memcached too many connections (> {{$memcachedConnectionThrottled.val}}%) (instance {{`{{`}} $labels.pod {{`}}`}})
        description: "More than {{$memcachedConnectionThrottled.val}}% of Memcached connections are throttled {{`{{`}} $labels.pod {{`}}`}}\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
    {{ $memcachedConnectionsNoneMinor := index (default dict .rules) "memcachedConnectionsNoneMinor" }}
    {{ if (and $memcachedConnectionsNoneMinor (include "memcached-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $memcachedConnectionsNoneMinor.enabled $memcachedConnectionsNoneMinor.severity))) -}}
    - alert: MemcachedConnectionsNoneMinor
      expr: memcached_current_connections{job="{{ $app }}-stats",namespace="{{ $.Release.Namespace }}"} == 0
      for: {{ $memcachedConnectionsNoneMinor.duration }}
      labels:
        severity: {{ $memcachedConnectionsNoneMinor.severity }}
        {{- include "memcached-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: Memcached no connection (instance {{`{{`}} $labels.pod {{`}}`}})
        description: "No connection to memcached {{`{{`}} $labels.pod {{`}}`}}\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
    {{ $memcachedItemsNoneMinor := index (default dict .rules) "memcachedItemsNoneMinor" }}
    {{ if (and $memcachedItemsNoneMinor (include "memcached-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $memcachedItemsNoneMinor.enabled $memcachedItemsNoneMinor.severity))) -}}
    - alert: MemcachedItemsNoneMinor
      expr: memcached_current_items{job="{{ $app }}-stats",namespace="{{ $.Release.Namespace }}"} == 0
      for: {{ $memcachedItemsNoneMinor.duration }}
      labels:
        severity: {{ $memcachedItemsNoneMinor.severity }}
        {{- include "memcached-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: Memcached has no item ({{$memcachedItemsNoneMinor.val}} second ago) (instance {{`{{`}} $labels.pod {{`}}`}})
        description: "Memcached has no item\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
    {{ $memcachedEvictionsLimit := index (default dict .rules) "memcachedEvictionsLimit" }}
    {{ if (and $memcachedEvictionsLimit (include "memcached-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $memcachedEvictionsLimit.enabled $memcachedEvictionsLimit.severity))) -}}
    - alert: memcachedEvictionsLimit
      expr: increase(memcached_items_evicted_total{job="{{ $app }}-stats",namespace="{{ $.Release.Namespace }}"}[1m]) > {{$memcachedEvictionsLimit.val}}
      for: {{ $memcachedEvictionsLimit.duration }}
      labels:
        severity: {{ $memcachedEvictionsLimit.severity }}
        {{- include "memcached-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: Memcached has high evictions per minute (> {{$memcachedEvictionsLimit.val}}) (instance {{`{{`}} $labels.pod {{`}}`}})
        description: "Memcached has high evictions on (instance {{`{{`}} $labels.pod {{`}}`}})\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
  {{ end -}}
  {{ end -}}


  {{ with .Values.form.alert.groups.provisioner -}}
  {{ if (include "memcached-alerts.alertGroupEnabled" (list $.Values.form.alert.enabled .)) -}}
  - name: memcached.provisioner.{{ $.Release.Namespace }}.{{ $app }}.rules
    rules:
    {{ $appPhaseNotReady := index (default dict .rules) "appPhaseNotReady" }}
    {{ if (and $appPhaseNotReady (include "memcached-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $appPhaseNotReady.enabled $appPhaseNotReady.severity))) -}}
    - alert: KubeDBMemcachedPhaseNotReady
      expr: kubedb_com_memcached_status_phase{phase="NotReady",app="{{ $app }}",namespace="{{ $.Release.Namespace }}"} == 1
      for: {{ $appPhaseNotReady.duration }}
      labels:
        severity: {{ $appPhaseNotReady.severity }}
        {{- include "memcached-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: KubeDB Memcached Phase NotReady (memcached {{`{{`}} $labels.memcached {{`}}`}})
        description: "KubeDB Memcached Phase not ready on {{`{{`}} $labels.memcached {{`}}`}}\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
    {{ $appPhaseCritical := index (default dict .rules) "appPhaseCritical" }}
    {{ if (and $appPhaseCritical (include "memcached-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $appPhaseCritical.enabled $appPhaseCritical.severity))) -}}
    - alert: KubeDBMemcachedPhaseCritical
      expr: kubedb_com_memcached_status_phase{phase="Critical",app="{{ $app }}",namespace="{{ $.Release.Namespace }}"} == 1
      for: {{ $appPhaseCritical.duration }}
      labels:
        severity: {{ $appPhaseCritical.severity }}
        {{- include "memcached-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: KubeDB Memcached Phase Critical (memcached {{`{{`}} $labels.memcached {{`}}`}})
        description: "KubeDB Memcached Phase Critical {{`{{`}} $labels.memcached {{`}}`}}\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
  {{ end -}}
  {{ end -}}

{{ end }}
