{{ $app := (include "pgpool-alerts.fullname" .) }}

{{ if (include "pgpool-alerts.alertsEnabled" .Values.form.alert.enabled) }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ $app }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "pgpool-alerts.labels" . | nindent 4 }}
{{- if .Values.form.alert.labels }}
    {{- toYaml .Values.form.alert.labels | nindent 4 }}
{{- end }}
{{- if .Values.form.alert.annotations }}
  annotations:
    {{- toYaml .Values.form.alert.annotations | nindent 4 }}
{{- end }}
spec:
  groups:
  {{ with .Values.form.alert.groups.database -}}
  {{ if (include "pgpool-alerts.alertGroupEnabled" (list $.Values.form.alert.enabled .)) -}}
  - name: pgpool.database.{{ $.Release.Namespace }}.{{ $app }}.rules
    rules:
    {{ $pgpoolTooManyConnections := index (default dict .rules) "pgpoolTooManyConnections" }}
    {{ if (and $pgpoolTooManyConnections (include "pgpool-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $pgpoolTooManyConnections.enabled $pgpoolTooManyConnections.severity))) -}}
    - alert: PgpoolTooManyConnections
      expr: (sum by (pod) (pgpool2_backend_by_process_total{namespace="{{ $.Release.Namespace }}",job="{{ $app }}-stats"}) / sum by (pod) (pgpool2_backend_total{namespace="{{ $.Release.Namespace }}",job="{{ $app }}-stats"})) > {{ $pgpoolTooManyConnections.val }}
      for: {{ $pgpoolTooManyConnections.duration }}
      labels:
        severity: {{ $pgpoolTooManyConnections.severity }}
        {{- include "pgpool-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: Pgpool too many connection usage (instance {{`{{`}} $labels.pod {{`}}`}})
        description: "Pgpool {{`{{`}} $labels.pod {{`}}`}} high connection usage\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
    {{ $pgpoolPostgresHealthCheckFailure := index (default dict .rules) "pgpoolPostgresHealthCheckFailure" }}
    {{ if (and $pgpoolPostgresHealthCheckFailure (include "pgpool-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $pgpoolPostgresHealthCheckFailure.enabled $pgpoolPostgresHealthCheckFailure.severity))) -}}
    - alert: PgpoolPostgresHealthCheckFailure
      expr: pgpool2_pool_health_check_stats_fail_count{job="{{ $app }}-stats",namespace="{{ $.Release.Namespace }}"} > {{ $pgpoolPostgresHealthCheckFailure.val }}
      for: {{ $pgpoolPostgresHealthCheckFailure.duration }}
      labels:
        severity: {{ $pgpoolPostgresHealthCheckFailure.severity }}
        {{- include "pgpool-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: Pgpool health check failed for backend PostgreSQL  (instance {{`{{`}} $labels.pod {{`}}`}}  {{`{{`}} $labels.role {{`}}`}})
        description: "Pgpool {{`{{`}} $labels.pod {{`}}`}}  health check failure for backend PosgreSQL {{`{{`}} $labels.role {{`}}`}} server\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
    {{ $pgpoolExporterLastScrapeError := index (default dict .rules) "pgpoolExporterLastScrapeError" }}
    {{ if (and $pgpoolExporterLastScrapeError (include "pgpool-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $pgpoolExporterLastScrapeError.enabled $pgpoolExporterLastScrapeError.severity))) -}}
    - alert: PgpoolExporterLastScrapeError
      expr: pgpool2_last_scrape_error{job="{{ $app }}-stats",namespace="{{ $.Release.Namespace }}"} > 0
      for: {{ $pgpoolExporterLastScrapeError.duration }}
      labels:
        severity: {{ $pgpoolExporterLastScrapeError.severity }}
        {{- include "pgpool-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: Pgpool exporter error (instance {{`{{`}} $labels.pod {{`}}`}})
        description: "Pgpool exporter is showing errors.\n  {{`{{`}} $labels.pod {{`}}`}}\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
    {{ $pgpoolBackendPanicMessageCount := index (default dict .rules) "pgpoolBackendPanicMessageCount" }}
    {{ if (and $pgpoolBackendPanicMessageCount (include "pgpool-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $pgpoolBackendPanicMessageCount.enabled $pgpoolBackendPanicMessageCount.severity))) -}}
    - alert: PgpoolBackendPanicMessageCount
      expr: pgpool2_pool_backend_stats_panic_cnt{job="{{ $app }}-stats",namespace="{{ $.Release.Namespace }}"} > {{ $pgpoolBackendPanicMessageCount.val }}
      for: {{ $pgpoolBackendPanicMessageCount.duration }}
      labels:
        severity: {{ $pgpoolBackendPanicMessageCount.severity }}
        {{- include "pgpool-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: Pgpool backend panic message (instance {{`{{`}} $labels.pod {{`}}`}}  {{`{{`}} $labels.role {{`}}`}})
        description: "Panic messages returned from postgres backend {{`{{`}} $labels.role {{`}}`}} of pgpool {{`{{`}} $labels.pod {{`}}`}}\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
    {{ $pgpoolBackendFatalMessageCount := index (default dict .rules) "pgpoolBackendFatalMessageCount" }}
    {{ if (and $pgpoolBackendFatalMessageCount (include "pgpool-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $pgpoolBackendFatalMessageCount.enabled $pgpoolBackendFatalMessageCount.severity))) -}}
    - alert: PgpoolBackendFatalMessageCount
      expr: pgpool2_pool_backend_stats_fatal_cnt{job="{{ $app }}-stats",namespace="{{ $.Release.Namespace }}"} > {{ $pgpoolBackendFatalMessageCount.val }}
      for: {{ $pgpoolBackendFatalMessageCount.duration }}
      labels:
        severity: {{ $pgpoolBackendFatalMessageCount.severity }}
        {{- include "pgpool-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: Pgpool backend fatal message (instance {{`{{`}} $labels.pod {{`}}`}}  {{`{{`}} $labels.role {{`}}`}})
        description: "Fatal messages returned from postgres backend {{`{{`}} $labels.role {{`}}`}} of pgpool {{`{{`}} $labels.pod {{`}}`}}\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
    {{ $pgpoolBackendErrorMessageCount := index (default dict .rules) "pgpoolBackendErrorMessageCount" }}
    {{ if (and $pgpoolBackendErrorMessageCount (include "pgpool-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $pgpoolBackendErrorMessageCount.enabled $pgpoolBackendErrorMessageCount.severity))) -}}
    - alert: PgpoolBackendErrorMessageCount
      expr: pgpool2_pool_backend_stats_error_cnt{job="{{ $app }}-stats",namespace="{{ $.Release.Namespace }}"} > {{ $pgpoolBackendErrorMessageCount.val }}
      for: {{ $pgpoolBackendErrorMessageCount.duration }}
      labels:
        severity: {{ $pgpoolBackendErrorMessageCount.severity }}
        {{- include "pgpool-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: Pgpool backend error message (instance {{`{{`}} $labels.pod {{`}}`}}  {{`{{`}} $labels.role {{`}}`}})
        description: "Error messages returned from postgres backend {{`{{`}} $labels.role {{`}}`}} of pgpool {{`{{`}} $labels.pod {{`}}`}}\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
    {{ $pgpoolLowCacheMemory := index (default dict .rules) "pgpoolLowCacheMemory" }}
    {{ if (and $pgpoolLowCacheMemory (include "pgpool-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $pgpoolLowCacheMemory.enabled $pgpoolLowCacheMemory.severity))) -}}
    - alert: PgpoolLowCacheMemory
      expr: pgpool2_pool_cache_free_cache_entries_size{job="{{ $app }}-stats",namespace="{{ $.Release.Namespace }}"} / 1000000 < {{ $pgpoolLowCacheMemory.val }}
      for: {{ $pgpoolLowCacheMemory.duration }}
      labels:
        severity: {{ $pgpoolLowCacheMemory.severity }}
        {{- include "pgpool-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: Low cache memory (instance {{`{{`}} $labels.pod {{`}}`}}
        description: "Pgpool have low cache memory remaining {{`{{`}} $labels.pod {{`}}`}}\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
    {{ $pgpoolDown := index (default dict .rules) "pgpoolDown" }}
    {{ if (and $pgpoolDown (include "pgpool-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $pgpoolDown.enabled $pgpoolDown.severity))) -}}
    - alert: PgpoolDown
      expr: pgpool2_up{job="{{- $app -}}-stats",namespace="{{ $.Release.Namespace }}"} == 0
      for: {{ $pgpoolDown.duration }}
      labels:
        severity: {{ $pgpoolDown.severity }}
        {{- include "pgpool-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: Pgpool instance down (instance {{`{{`}} $labels.pod {{`}}`}})
        description: "Pgpool instance is down {{`{{`}} $labels.pod {{`}}`}}\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
  {{end -}}
  {{end -}}


  {{ with .Values.form.alert.groups.provisioner -}}
  {{ if (include "pgpool-alerts.alertGroupEnabled" (list $.Values.form.alert.enabled .)) -}}
  - name: pgpool.provisioner.{{ $.Release.Namespace }}.{{ $app }}.rules
    rules:
    {{ $appPhaseNotReady := index (default dict .rules) "appPhaseNotReady" }}
    {{ if (and $appPhaseNotReady (include "pgpool-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $appPhaseNotReady.enabled $appPhaseNotReady.severity))) -}}
    - alert: KubeDBPgpoolPhaseNotReady
      expr: kubedb_com_pgpool_status_phase{phase="NotReady",app="{{ $app }}",namespace="{{ $.Release.Namespace }}"} == 1
      for: {{ $appPhaseNotReady.duration }}
      labels:
        severity: {{ $appPhaseNotReady.severity }}
        {{- include "pgpool-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: KubeDB Pgpool Phase NotReady (pgpool {{`{{`}} $labels.pgpool {{`}}`}})
        description: "KubeDB Pgpool Phase not ready on {{`{{`}} $labels.pgpool {{`}}`}}\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{ end -}}
    {{ $appPhaseCritical := index (default dict .rules) "appPhaseCritical" }}
    {{ if (and $appPhaseCritical (include "pgpool-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $appPhaseCritical.enabled $appPhaseCritical.severity))) -}}
    - alert: KubeDBPgpoolPhaseCritical
      expr: kubedb_com_pgpool_status_phase{phase="Critical",app="{{ $app }}",namespace="{{ $.Release.Namespace }}"} == 1
      for: {{ $appPhaseCritical.duration }}
      labels:
        severity: {{ $appPhaseCritical.severity }}
        {{- include "pgpool-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: KubeDB Pgpool Phase Critical (pgpool {{`{{`}} $labels.pgpool {{`}}`}})
        description: "KubeDB Pgpool Phase Critical {{`{{`}} $labels.pgpool {{`}}`}}\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
  {{ end -}}
  {{ end -}}

{{ end }}
