apiVersion: v2
name: clickhouse-alerts
description: A Helm chart for ClickHouse Alert by AppsCode
type: application
version: v2026.7.14
appVersion: v0.7.0
home: https://github.com/appscode/alerts
icon: https://cdn.appscode.com/images/products/kubedb/kubedb-icon.png
sources:
- https://github.com/appscode/alerts
maintainers:
- name: appscode
  email: support@appscode.com
