{{ $app := (include "oracle-alerts.fullname" .) }}

{{ if (include "oracle-alerts.alertsEnabled" .Values.form.alert.enabled) }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ $app }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "oracle-alerts.labels" . | nindent 4 }}
{{- if .Values.form.alert.labels }}
    {{- toYaml .Values.form.alert.labels | nindent 4 }}
{{- end }}
{{- if .Values.form.alert.annotations }}
  annotations:
    {{- toYaml .Values.form.alert.annotations | nindent 4 }}
{{- end }}
spec:
  groups:
  {{ with .Values.form.alert.groups.database -}}
  {{ if (include "oracle-alerts.alertGroupEnabled" (list $.Values.form.alert.enabled .)) -}}
  - name: oracle.database.{{ $.Release.Namespace }}.{{ $app }}.rules
    rules:
    {{ $oracleInstanceDown := index (default dict .rules) "oracleInstanceDown" }}
    {{ if (and $oracleInstanceDown (include "oracle-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $oracleInstanceDown.enabled $oracleInstanceDown.severity))) -}}
    - alert: OracleInstanceDown
      expr: up{job="{{- $app -}}-stats",namespace="{{ $.Release.Namespace }}"} == 0
      for: {{ $oracleInstanceDown.duration }}
      labels:
        severity: {{ $oracleInstanceDown.severity }}
        {{- include "oracle-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: Oracle instance down (instance {{`{{`}} $labels.pod {{`}}`}})
        description: "Oracle instance is down on {{`{{`}} $labels.pod {{`}}`}}\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{end -}}
    {{ $oracleServiceDown := index (default dict .rules) "oracleServiceDown" }}
    {{ if (and $oracleServiceDown (include "oracle-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $oracleServiceDown.enabled $oracleServiceDown.severity))) -}}
    - alert: OracleServiceDown
      expr: sum by (service) (up{job="{{ $app }}-stats",namespace="{{ $.Release.Namespace }}"}) == 0
      for: {{ $oracleServiceDown.duration }}
      labels:
        severity: {{ $oracleServiceDown.severity }}
        {{- include "oracle-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: Oracle service down (instance {{`{{`}} $labels.pod {{`}}`}})
        description: "Oracle service is down on {{`{{`}} $labels.pod {{`}}`}}\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
    {{ $oracleRestarted := index (default dict .rules) "oracleRestarted" }}
    {{ if (and $oracleRestarted (include "oracle-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $oracleRestarted.enabled $oracleRestarted.severity))) -}}
    - alert: OracleRestarted
      expr: oracledb_uptime_uptime_seconds{job="{{- $app -}}-stats",namespace="{{ $.Release.Namespace }}"} < {{ $oracleRestarted.val }}
      for: {{ $oracleRestarted.duration }}
      labels:
        severity: {{ $oracleRestarted.severity }}
        {{- include "oracle-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: Oracle restarted (instance {{`{{`}} $labels.pod {{`}}`}})
        description: "Oracle restarted\n  {{`{{`}} $labels.pod {{`}}`}}\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{end -}}
    {{ $diskUsageHigh := index (default dict .rules) "diskUsageHigh" }}
    {{ if (and $diskUsageHigh (include "oracle-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $diskUsageHigh.enabled $diskUsageHigh.severity))) -}}
    - alert: DiskUsageHigh
      expr: |
        (kubelet_volume_stats_used_bytes{job=~"kubelet"} / on(persistentvolumeclaim) group_left(pod) (
          kubelet_volume_stats_capacity_bytes{job=~"kubelet"} + on(persistentvolumeclaim) group_left(pod)
          kube_pod_spec_volumes_persistentvolumeclaims_info{pod=~"{{ $.Release.Name }}-.+$", namespace=~"{{ $.Release.Namespace }}"}
        )) * 100 > {{ $diskUsageHigh.val }}
      for: {{ $diskUsageHigh.duration }}
      labels:
        severity: {{ $diskUsageHigh.severity }}
        {{- include "oracle-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: Persistent Volume Usages in instance {{`{{`}} $labels.instance {{`}}`}}
        description: "Persistent Volume Usages\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
    {{ $diskAlmostFull := index (default dict .rules) "diskAlmostFull" }}
    {{ if (and $diskAlmostFull (include "oracle-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $diskAlmostFull.enabled $diskAlmostFull.severity))) -}}
    - alert: DiskAlmostFull
      expr: |
        (kubelet_volume_stats_used_bytes{job=~"kubelet"} / on(persistentvolumeclaim) group_left(pod) (
        kubelet_volume_stats_capacity_bytes{job=~"kubelet"} + on(persistentvolumeclaim) group_left(pod)
        kube_pod_spec_volumes_persistentvolumeclaims_info{pod=~"{{ $.Release.Name }}-.+$", namespace=~"{{ $.Release.Namespace }}"}
        )) * 100 > {{ $diskAlmostFull.val }}
      for: {{ $diskAlmostFull.duration }}
      labels:
        severity: {{ $diskAlmostFull.severity }}
        {{- include "oracle-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: Persistent Volume Usages in instance {{`{{`}} $labels.instance {{`}}`}}
        description: "Persistent Volume Usages\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
  {{ end -}}
  {{ end -}}


  {{ with .Values.form.alert.groups.provisioner -}}
  {{ if (include "oracle-alerts.alertGroupEnabled" (list $.Values.form.alert.enabled .)) -}}
  - name: oracle.provisioner.{{ $.Release.Namespace }}.{{ $app }}.rules
    rules:
    {{ $appPhaseNotReady := index (default dict .rules) "appPhaseNotReady" }}
    {{ if (and $appPhaseNotReady (include "oracle-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $appPhaseNotReady.enabled $appPhaseNotReady.severity))) -}}
    - alert: KubeDBOraclePhaseNotReady
      expr: kubedb_com_oracle_status_phase{phase="NotReady",app="{{ $app }}",namespace="{{ $.Release.Namespace }}"} == 1
      for: {{ $appPhaseNotReady.duration }}
      labels:
        severity: {{ $appPhaseNotReady.severity }}
        {{- include "oracle-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: KubeDB Oracle Phase NotReady (oracle {{`{{`}} $labels.oracle {{`}}`}})
        description: "KubeDB Oracle Phase not ready on {{`{{`}} $labels.oracle {{`}}`}}\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{ end -}}
    {{ $appPhaseCritical := index (default dict .rules) "appPhaseCritical" }}
    {{ if (and $appPhaseCritical (include "oracle-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $appPhaseCritical.enabled $appPhaseCritical.severity))) -}}
    - alert: KubeDBOraclePhaseCritical
      expr: kubedb_com_oracle_status_phase{phase="Critical",app="{{ $app }}",namespace="{{ $.Release.Namespace }}"} == 1
      for: {{ $appPhaseCritical.duration }}
      labels:
        severity: {{ $appPhaseCritical.severity }}
        {{- include "oracle-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: KubeDB Oracle Phase Critical (oracle {{`{{`}} $labels.oracle {{`}}`}})
        description: "KubeDB Oracle Phase Critical {{`{{`}} $labels.oracle {{`}}`}}\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
  {{ end -}}
  {{ end -}}


  {{ with .Values.form.alert.groups.opsManager -}}
  {{ if (include "oracle-alerts.alertGroupEnabled" (list $.Values.form.alert.enabled .)) -}}
  - name: oracle.opsManager.{{ $.Release.Namespace }}.{{ $app }}.rules
    rules:
    {{ $opsRequestOnProgress := index (default dict .rules) "opsRequestOnProgress" }}
    {{ if (and $opsRequestOnProgress (include "oracle-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $opsRequestOnProgress.enabled $opsRequestOnProgress.severity))) -}}
    - alert: KubeDBOracleOpsRequestOnProgress
      expr: ops_kubedb_com_oracleopsrequest_status_phase{phase="Progressing",app="{{ $app }}",namespace="{{ $.Release.Namespace }}"} == 1
      for: {{ $opsRequestOnProgress.duration }}
      labels:
        severity: {{ $opsRequestOnProgress.severity }}
        {{- include "oracle-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: OracleOpsRequest on progress (oracleopsrequest {{`{{`}} $labels.oracleopsrequest {{`}}`}})
        description: "OracleOpsRequest {{`{{`}} $labels.oracleopsrequest {{`}}`}} is in progressressing status\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{ end -}}
    {{ $opsRequestStatusProgressingToLong := index (default dict .rules) "opsRequestStatusProgressingToLong" }}
    {{ if (and $opsRequestStatusProgressingToLong (include "oracle-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $opsRequestStatusProgressingToLong.enabled $opsRequestStatusProgressingToLong.severity))) -}}
    - alert: KubeDBOracleOpsRequestStatusProgressingToLong
      expr: ops_kubedb_com_oracleopsrequest_status_phase{phase="Progressing",app="{{ $app }}",namespace="{{ $.Release.Namespace }}"} == 1
      for: {{ $opsRequestStatusProgressingToLong.duration }}
      labels:
        severity: {{ $opsRequestStatusProgressingToLong.severity }}
        {{- include "oracle-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: OracleOpsRequest is in progressing status for too long (oracleopsrequest {{`{{`}} $labels.oracleopsrequest {{`}}`}})
        description: "OracleOpsRequest {{`{{`}} $labels.oracleopsrequest {{`}}`}} is in progressing status for too long\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{ end -}}
    {{ $opsRequestFailed := index (default dict .rules) "opsRequestFailed" }}
    {{ if (and $opsRequestFailed (include "oracle-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $opsRequestFailed.enabled $opsRequestFailed.severity))) -}}
    - alert: KubeDBOracleOpsRequestFailed
      expr: ops_kubedb_com_oracleopsrequest_status_phase{phase="Failed",app="{{ $app }}",namespace="{{ $.Release.Namespace }}"} == 1
      for: {{ $opsRequestFailed.duration }}
      labels:
        severity: {{ $opsRequestFailed.severity }}
        {{- include "oracle-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: OracleOpsRequest failed (oracleopsrequest {{`{{`}} $labels.oracleopsrequest {{`}}`}})
        description: "OracleOpsRequest {{`{{`}} $labels.oracleopsrequest {{`}}`}} failed \n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
  {{ end -}}
  {{ end -}}
{{ end }}