{{ $app := (include "solr-alerts.fullname" .) }}

{{ if (include "solr-alerts.alertsEnabled" .Values.form.alert.enabled) }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ $app }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "solr-alerts.labels" . | nindent 4 }}
{{- if .Values.form.alert.labels }}
    {{- toYaml .Values.form.alert.labels | nindent 4 }}
{{- end }}
{{- if .Values.form.alert.annotations }}
annotations:
    {{- toYaml .Values.form.alert.annotations | nindent 4 }}
{{- end }}
spec:
  groups:
  {{ with .Values.form.alert.groups.database -}}
  {{ if (include "solr-alerts.alertGroupEnabled" (list $.Values.form.alert.enabled .)) -}}
  - name: solr.database.{{ $.Release.Namespace }}.{{ $app }}.rules
    rules:
    {{ $solrDownShards := index (default dict .rules) "solrDownShards" }}
    {{ if (and $solrDownShards (include "solr-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $solrDownShards.enabled $solrDownShards.severity))) -}}
    - alert: SolrDownShards
      expr: count(max by (core) (solr_collections_replica_state{namespace="{{ $.Release.Namespace }}",job="{{ $app }}-stats",state="down"})) OR on() vector(0) != 0
      for: {{ $solrDownShards.duration }}
      labels:
        severity: {{ $solrDownShards.severity }}
        {{- include "solr-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: Solr shards down (instance {{`{{`}} $labels.pod {{`}}`}})
        description: "Solr shards down on {{`{{`}} $labels.pod {{`}}`}}\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
    {{ $solrRecoveryFailedShards := index (default dict .rules) "solrRecoveryFailedShards" }}
    {{ if (and $solrRecoveryFailedShards (include "solr-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $solrRecoveryFailedShards.enabled $solrRecoveryFailedShards.severity))) -}}
    - alert: SolrRecoveryFailedShards
      expr: count(max by (core) (solr_collections_replica_state{namespace="{{ $.Release.Namespace }}",job="{{ $app }}-stats",state="recovery_failed"})) OR on() vector(0) != 0
      for: {{ $solrRecoveryFailedShards.duration }}
      labels:
        severity: {{ $solrRecoveryFailedShards.severity }}
        {{- include "solr-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: Solr shards recovery failed (instance {{`{{`}} $labels.pod {{`}}`}})
        description: "Solr shard recovery failed on {{`{{`}} $labels.pod {{`}}`}}\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
    {{ $solrHighThreadRunning := index (default dict .rules) "solrHighThreadRunning" }}
    {{ if (and $solrHighThreadRunning (include "solr-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $solrHighThreadRunning.enabled $solrHighThreadRunning.severity))) -}}
    - alert: SolrHighThreadRunning
      expr: solr_metrics_jvm_threads{namespace="{{ $.Release.Namespace }}",job="{{ $app }}-stats"} > {{ $solrHighThreadRunning.val }}
      for: {{ $solrHighThreadRunning.duration }}
      labels:
        severity: {{ $solrHighThreadRunning.severity }}
        {{- include "solr-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: Solr high thread running (instance {{`{{`}} $labels.pod {{`}}`}})
        description: "Solr high thread running on {{`{{`}} $labels.pod {{`}}`}}\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
    {{ $solrHighPoolSize := index (default dict .rules) "solrHighPoolSize" }}
    {{ if (and $solrHighPoolSize (include "solr-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $solrHighPoolSize.enabled $solrHighPoolSize.severity))) -}}
    - alert: SolrHighPoolSize
      expr: solr_metrics_jvm_memory_pools_bytes{namespace="{{ $.Release.Namespace }}",job="{{ $app }}-stats"} > {{ $solrHighPoolSize.val }}
      for: {{ $solrHighPoolSize.duration }}
      labels:
        severity: {{ $solrHighPoolSize.severity }}
        {{- include "solr-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: Solr high pool size (instance {{`{{`}} $labels.pod {{`}}`}})
        description: "Solr high pool size {{`{{`}} $labels.pod {{`}}`}}\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
    {{ $solrHighQPS := index (default dict .rules) "solrHighQPS" }}
    {{ if (and $solrHighQPS (include "solr-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $solrHighQPS.enabled $solrHighQPS.severity))) -}}
    - alert: SolrHighQPS
      expr: sum by (collection) (solr_metrics_core_query_1minRate{namespace="{{ $.Release.Namespace }}",job="{{ $app }}-stats"}) > {{ $solrHighQPS.val }}
      for: {{ $solrHighQPS.duration }}
      labels:
        severity: {{ $solrHighQPS.severity }}
        {{- include "solr-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: Solr high QPS (instance {{`{{`}} $labels.pod {{`}}`}})
        description: "Solr high QPS {{`{{`}} $labels.pod {{`}}`}}\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
    {{ $solrHighHeapSize := index (default dict .rules) "solrHighHeapSize" }}
    {{ if (and $solrHighHeapSize (include "solr-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $solrHighHeapSize.enabled $solrHighHeapSize.severity))) -}}
    - alert: SolrHighHeapSize
      expr: solr_metrics_jvm_memory_heap_bytes{namespace="{{ $.Release.Namespace }}",job="{{ $app }}-stats"} > {{ $solrHighHeapSize.val }}
      for: {{ $solrHighHeapSize.duration }}
      labels:
        severity: {{ $solrHighHeapSize.severity }}
        {{- include "solr-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: Solr high heap size (instance {{`{{`}} $labels.pod {{`}}`}})
        description: "Solr high heap size {{`{{`}} $labels.pod {{`}}`}}\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
    {{ $solrHighBufferSize := index (default dict .rules) "solrHighBufferSize" }}
    {{ if (and $solrHighBufferSize (include "solr-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $solrHighBufferSize.enabled $solrHighBufferSize.severity))) -}}
    - alert: SolrHighBufferSize
      expr: solr_metrics_jvm_buffers_bytes{namespace="{{ $.Release.Namespace }}",job="{{ $app }}-stats"} > {{ $solrHighBufferSize.val }}
      for: {{ $solrHighBufferSize.duration }}
      labels:
        severity: {{ $solrHighBufferSize.severity }}
        {{- include "solr-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: Solr high buffer size (instance {{`{{`}} $labels.pod {{`}}`}})
        description: "Solr high buffer size {{`{{`}} $labels.pod {{`}}`}}\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
    {{ $diskUsageHigh := index (default dict .rules) "diskUsageHigh" }}
    {{ if (and $diskUsageHigh (include "solr-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $diskUsageHigh.enabled $diskUsageHigh.severity))) -}}
    - alert: DiskUsageHigh
      expr: (kubelet_volume_stats_used_bytes{service="kubernetes"} / on(persistentvolumeclaim) group_left(pod) ((kubelet_volume_stats_used_bytes{service="kubernetes"} + on(persistentvolumeclaim) group_left(pod) kube_pod_spec_volumes_persistentvolumeclaims_info{pod=~"{{ $.Release.Name }}-.+$",namespace=~"{{ $.Release.Namespace }}"}) ) )
        * 100 > {{ $diskUsageHigh.val }}
      for: {{ $diskUsageHigh.duration }}
      labels:
        severity: {{ $diskUsageHigh.severity }}
        {{- include "solr-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: Persistent Volume Usages in instance {{`{{`}} $labels.instance {{`}}`}}
        description: "Persistent Volume Usages\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
    {{ $diskAlmostFull := index (default dict .rules) "diskAlmostFull" }}
    {{ if (and $diskAlmostFull (include "solr-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $diskAlmostFull.enabled $diskAlmostFull.severity))) -}}
    - alert: DiskAlmostFull
      expr: (kubelet_volume_stats_used_bytes{service="kubernetes"} / on(persistentvolumeclaim) group_left(pod) ((kubelet_volume_stats_used_bytes{service="kubernetes"} + on(persistentvolumeclaim) group_left(pod) kube_pod_spec_volumes_persistentvolumeclaims_info{pod=~"{{ $.Release.Name }}-.+$",namespace=~"{{ $.Release.Namespace }}"}) ) )
        * 100 > {{ $diskAlmostFull.val }}
      for: {{ $diskAlmostFull.duration }}
      labels:
        severity: {{ $diskAlmostFull.severity }}
        {{- include "solr-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: Persistent Volume Usages in instance {{`{{`}} $labels.instance {{`}}`}}
        description: "Persistent Volume Usages\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
  {{ end -}}
  {{ end -}}
  
  {{ with .Values.form.alert.groups.provisioner -}}
  {{ if (include "solr-alerts.alertGroupEnabled" (list $.Values.form.alert.enabled .)) -}}
  - name: solr.provisioner.{{ $.Release.Namespace }}.{{ $app }}.rules
    rules:
    {{ $appPhaseNotReady := index (default dict .rules) "appPhaseNotReady" }}
    {{ if (and $appPhaseNotReady (include "solr-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $appPhaseNotReady.enabled $appPhaseNotReady.severity))) -}}
    - alert: KubeDBSolrPhaseNotReady
      expr: kubedb_com_solr_status_phase{phase="NotReady",app="{{ $app }}",namespace="{{ $.Release.Namespace }}"} == 1
      for: {{ $appPhaseNotReady.duration }}
      labels:
        severity: {{ $appPhaseNotReady.severity }}
        {{- include "solr-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: KubeDB solr Phase NotReady (solr {{`{{`}} $labels.solr {{`}}`}})
        description: "KubeDB solr Phase not ready on {{`{{`}} $labels.solr {{`}}`}}\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
    {{ $appPhaseCritical := index (default dict .rules) "appPhaseCritical" }}
    {{ if (and $appPhaseCritical (include "solr-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled $appPhaseCritical.enabled $appPhaseCritical.severity))) -}}
    - alert: KubeDBSolrPhaseCritical
      expr: kubedb_com_solr_status_phase{phase="Critical",app="{{ $app }}",namespace="{{ $.Release.Namespace }}"} == 1
      for: {{ $appPhaseCritical.duration }}
      labels:
        severity: {{ $appPhaseCritical.severity }}
        {{- include "solr-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: KubeDB solr Phase Critical (solr {{`{{`}} $labels.solr {{`}}`}})
        description: "KubeDB solr Phase Critical {{`{{`}} $labels.solr {{`}}`}}\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
  {{ end -}}
  {{ end -}}

{{ end }}


